src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <recordTypes>
        <fullName>Audience</fullName>
        <active>true</active>
        <description>Configure a new Audience to segment records.</description>
        <label>Audience</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CMSUserSettings__c.object
<CustomObject>
    <fields>
        <fullName>AudienceAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AudienceContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS User Settings</label>
    <nameField>
        <label>CMS User Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Users Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CMS.cls
public with sharing class CMS {

    public static String prefix = '';

    //This methods updates the CMS User Settings with the audiences calculation
    public static void updateUserSettings(Id userId, Id clusterId, Id accountId, Id contactId, Id acRelationId, Id customRecordId){
        User user;
        try{user = [SELECT Id, UserName FROM User WHERE Id =: userId];}catch(Exception e){}
        
        Cluster__c cluster;
        try{cluster = [SELECT Id FROM Cluster__c WHERE Id =: clusterId];}catch(Exception e){}
        
        if(user != null){
            if(cluster != null){
                CMSUserSettings__c userSettings = getUserSettings(userId);
                
                //CMS User Settings creation
                if(userSettings == null){
                    userSettings = new CMSUserSettings__c(
                        Name = user.UserName,
                        User__c = user.Id
                    );
                }
                userSettings.Cluster__c = cluster.Id;
                userSettings.AudienceAccount__c = accountId;
                userSettings.AudienceContact__c = contactId;

                //Calculate User Audiences
                map<Id, Audience__c> audiencesMap = new map<Id, Audience__c>([SELECT Id FROM Audience__c WHERE RecordType.DeveloperName = 'Audience' AND Cluster__c =: userSettings.Cluster__c AND Status__c = 'Active']);
                List<String> userAudiences = AudienceUtils.audienceUserCalculation(audiencesMap.keySet(), userSettings.AudienceAccount__c, userSettings.AudienceContact__c, acRelationId, customRecordId);
                userSettings.Audiencies__c = String.join(userAudiences, ';');

                //Upsert CMS User Settings
                upsert userSettings;

                CMSUsersSettingsMap.put(user.Id, userSettings);
            }else{
                throw new CMSException('CLUSTER_NOT_FOUND: ' + Label.ExceptionMessageClusterNotFound);
            }
        }else{
            throw new CMSException('USER_NOT_FOUND' + Label.ExceptionMessageUserNotFound);
        }
    }

    //This methods returns the CMS User Settings from a User Id
    private static map<Id, CMSUserSettings__c> CMSUsersSettingsMap;
    public static CMSUserSettings__c getUserSettings(Id userId){
        if(CMSUsersSettingsMap == null){
            CMSUsersSettingsMap = new map<Id, CMSUserSettings__c>();
        }
        if(!CMSUsersSettingsMap.containsKey(userId)){
            try{CMSUsersSettingsMap.put(userId, [SELECT Id, User__c, Cluster__c, Audiencies__c FROM CMSUserSettings__c WHERE User__c =: userId]);}catch(Exception e){}
        }
        
        return CMSUsersSettingsMap.get(userId);
    }

    //This methods returns a set of Audiences External Ids of a User
    public static set<String> getUserAudiences(Id userId){
        set<String> userAudiencesSet = new set<String>();
        if(getUserSettings(userId).Audiencies__c != null){
            userAudiencesSet.addAll(getUserSettings(userId).Audiencies__c.split(';'));
        }
        return userAudiencesSet;
    }
}