src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AudienceCriterion__c.object
<CustomObject>
    <fields>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <referenceTo>Audience__c</referenceTo>
        <relationshipLabel>Audience Criteria</relationshipLabel>
        <relationshipName>AudienceCriteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <label>Field API Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MainObjectType__c</fullName>
        <label>Main Object Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equals</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>greater or equal than</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>less or equal than</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>not contains</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ValueType__c</fullName>
        <label>Value Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Audience Criterion</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Audience Criterion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CMSUserSettings__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS User Settings</label>
    <nameField>
        <label>CMS User Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Users Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CMSTest.cls
@isTest(seeAllData = false)
public class CMSTest {
	
    @testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
	}

	@isTest 
	static void updateUserSettings(){
		/* Comment: Checks if the settings is created and the audiences are calculated */

		//Given
        User u = [SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId()];
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience);
		insert audienceTest;
		AudienceCriterion__c audCriterionTest = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'User', Operator__c = 'equals', Order__c = 1, Value__c = u.Name, ValueType__c = 'Text');
        insert audCriterionTest;
        audienceTest.Status__c = 'Active';
        update audienceTest;

		//When
		Test.startTest();
		CMS.updateUserSettings(u.Id, clusterList[0].Id, null, null, null, u.Id);
		Test.stopTest();

		//Then
		CMSUserSettings__c CMSUserSettings = [SELECT Audiencies__c FROM CMSUserSettings__c];
        Audience__c audienceTestPost = [SELECT ExternalId__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertEquals(audienceTestPost.ExternalId__c, CMSUserSettings.Audiencies__c);
	}

    @isTest 
	static void getUserSettings(){
		/* Comment: Checks if the the methods getUserSettings returns the CMS User Settings from a User Id */

		//Given
        User u = [SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId()];
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience);
		insert audienceTest;
		AudienceCriterion__c audCriterionTest = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'User', Operator__c = 'equals', Order__c = 1, Value__c = u.Name, ValueType__c = 'Text');
        insert audCriterionTest;
        audienceTest.Status__c = 'Active';
        update audienceTest;
        CMS.updateUserSettings(u.Id, clusterList[0].Id, null, null, null, u.Id);

		//When
		Test.startTest();
		CMSUserSettings__c CMSUserSettings = CMS.getUserSettings(u.Id);
		Test.stopTest();

		//Then
		System.assertEquals(u.Id, CMSUserSettings.User__c);
	}

	@isTest 
	static void getUserAudiences(){
		/* Comment: Checks if the methods getUserAudiences returns a set of Audiences External Ids of a User */

		//Given
        User u = [SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId()];
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience);
		insert audienceTest;
		AudienceCriterion__c audCriterionTest = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'User', Operator__c = 'equals', Order__c = 1, Value__c = u.Name, ValueType__c = 'Text');
        insert audCriterionTest;
        audienceTest.Status__c = 'Active';
        update audienceTest;
        CMS.updateUserSettings(u.Id, clusterList[0].Id, null, null, null, u.Id);

		//When
		Test.startTest();
		Set<String> audiencesSet = CMS.getUserAudiences(u.Id);
		Test.stopTest();

		//Then
		Audience__c audienceTestPost = [SELECT ExternalId__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertEquals(1, audiencesSet.size());
		System.assert(audiencesSet.contains(audienceTestPost.ExternalId__c));
	}

}