src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>AudienceCriteria__c</fullName>
        <label>Audience Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MatchCriteria__c</fullName>
        <inlineHelpText>Match Criteria governs how and when filters apply to your criteria. Use AND and OR operators to fine-tune your results.</inlineHelpText>
        <label>Match Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReferenceAudienceExternalIds__c</fullName>
        <label>Reference Audience External Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <recordTypes>
        <fullName>Audience</fullName>
        <active>true</active>
        <description>Configure a new Audience to segment records.</description>
        <label>Audience</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AudienceCriterion__c.object
<CustomObject>
    <fields>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <referenceTo>Audience__c</referenceTo>
        <relationshipLabel>Audience Criteria</relationshipLabel>
        <relationshipName>AudienceCriteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <label>Field API Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MainObjectType__c</fullName>
        <label>Main Object Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equals</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>greater or equal than</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>less or equal than</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>not contains</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ValueType__c</fullName>
        <label>Value Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Audience Criterion</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Audience Criterion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MatchCriteria__c</fullName>
        <label>Match Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                    <default>true</default>
                    <label>All</label>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HTMLContent__c</fullName>
        <inlineHelpText>If html content wants to be uploaded use this field instead of the Long Description one.</inlineHelpText>
        <label>HTML Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AudienceUtilsTest.cls
@isTest(seeAllData = false)
public class AudienceUtilsTest {
    
    @testSetup
    static void generateCustomSettings(){
        User u = [SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId()];

        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> clusterRoot = MockupFactory.createCluster('Cluster Root', '', 1, 'ClusterRoot', 'CRT');
        List<Cluster__c> clusterGroup = MockupFactory.createCluster('Cluster Group', clusterRoot.get(0).id, 1, 'ClusterGroup', 'CGT');
        List<Cluster__c> clusterLeaf = MockupFactory.createCluster('Cluster Leaf', clusterGroup.get(0).id, 2, 'ClusterLeaf', 'CLT');
        List<Component__c> componentList = MockupFactory.createComponent('Banner', 1, clusterRoot[0]);
        List<Content__c> contentList = MockupFactory.createContent('Banner', clusterLeaf[0], 2);
        MockupFactory.createContentAssignment(contentList, componentList);

        //Apply Audience for User "All"
        Audience__c audienceTest = new Audience__c(Cluster__c = clusterLeaf[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience, MatchCriteria__c = 'All');
        insert audienceTest;
        AudienceCriterion__c audCriterionTest = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'User', Operator__c = 'equals', Order__c = 1, Value__c = u.Name, ValueType__c = 'Text');
        insert audCriterionTest;
        audienceTest.Status__c = 'Active';
        update audienceTest;

        //Not apply Audience for User "Any"
        Audience__c audienceTest2 = new Audience__c(Cluster__c = clusterLeaf[0].Id, Name = 'Test2', RecordTypeId = AudienceUtils.rtAudience, MatchCriteria__c = 'Any');
        insert audienceTest2;
        AudienceCriterion__c audCriterionTest2 = new AudienceCriterion__c(Audience__c = audienceTest2.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'User', Operator__c = 'contains', Order__c = 1, Value__c = u.Name + ' some text', ValueType__c = 'Text');
        insert audCriterionTest2;
		AudienceCriterion__c audCriterionTest2_1 = new AudienceCriterion__c(Audience__c = audienceTest2.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'User', Operator__c = 'not equals', Order__c = 2, Value__c = u.Name, ValueType__c = 'Text');
        insert audCriterionTest2_1;
		AudienceCriterion__c audCriterionTest2_2 = new AudienceCriterion__c(Audience__c = audienceTest2.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'User', Operator__c = 'not contains', Order__c = 3, Value__c = u.Name, ValueType__c = 'Text');
        insert audCriterionTest2_2;
		AudienceCriterion__c audCriterionTest2_3 = new AudienceCriterion__c(Audience__c = audienceTest2.Id, FieldAPIName__c = 'IsActive', MainObjectType__c = 'User', Operator__c = 'not equals', Order__c = 4, Value__c = 'TRUE', ValueType__c = 'Checkbox');
        insert audCriterionTest2_3;
        audienceTest2.Status__c = 'Active';
        update audienceTest2;

        //Apply Audience for User "Custom"
        Audience__c audienceTest3 = new Audience__c(Cluster__c = clusterLeaf[0].Id, Name = 'Test3', RecordTypeId = AudienceUtils.rtAudience, MatchCriteria__c = 'Custom', AudienceCriteria__c = '1');
        insert audienceTest3;
        AudienceCriterion__c audCriterionTest3 = new AudienceCriterion__c(Audience__c = audienceTest3.Id, FieldAPIName__c = 'IsActive', MainObjectType__c = 'User', Operator__c = 'equals', Order__c = 1, Value__c = 'TRUE', ValueType__c = 'Checkbox');
        insert audCriterionTest3;
        audienceTest3.Status__c = 'Active';
        update audienceTest3;

        CMS.updateUserSettings(u.Id, clusterLeaf[0].Id, null, null, null, u.Id);
    }

    @isTest 
    static void filterRecords(){
        /* Comment: Checks if the method filterRecords filter the records received based on the Audiences of a User */

        //Given
        Audience__c audienceTest = [SELECT Id, Cluster__c, ExternalId__c FROM Audience__c WHERE Name = 'Test' AND RecordTypeId =: AudienceUtils.rtAudience];
        Audience__c audienceTest2 = [SELECT Id, Cluster__c, ExternalId__c FROM Audience__c WHERE Name = 'Test2' AND RecordTypeId =: AudienceUtils.rtAudience];
        List<Content__c> contentList = [SELECT Id, HTMLContent__c FROM Content__c];
        contentList[0].Audience__c = AudienceUtils.audienceGroupCreation(new List<String>{audienceTest.ExternalId__c}, audienceTest.Cluster__c);
        contentList[1].Audience__c = AudienceUtils.audienceGroupCreation(new List<String>{audienceTest2.ExternalId__c}, audienceTest2.Cluster__c);
        update contentList;
        List<Content__c> contentListToFilter = [SELECT Id, Name, Audience__r.ReferenceAudienceExternalIds__c FROM Content__c];

        //When
        Test.startTest();
        AudienceUtils.filterRecords(UserInfo.getUserId(), contentListToFilter, 'Audience__c');
        Test.stopTest();

        //Then
        System.assertEquals(1, contentListToFilter.size());
        System.assertEquals('Banner 0', contentListToFilter[0].Name);
    }

    @isTest 
    static void audienceGroupCreation(){
        /* Comment: Checks if the method audienceGroupCreation returns o creates and return an Audience Group based on a combination of Audiences */

        //Given
        Audience__c audienceTest = [SELECT Id, Cluster__c, ExternalId__c FROM Audience__c WHERE Name = 'Test' AND RecordTypeId =: AudienceUtils.rtAudience];
        Audience__c audienceTest2 = [SELECT Id, Cluster__c, ExternalId__c FROM Audience__c WHERE Name = 'Test2' AND RecordTypeId =: AudienceUtils.rtAudience];

        //When
        Test.startTest();
        //Creation of groups
        AudienceUtils.audienceGroupCreation(new List<String>{audienceTest.ExternalId__c}, audienceTest.Cluster__c);
        AudienceUtils.audienceGroupCreation(new List<String>{audienceTest2.ExternalId__c}, audienceTest2.Cluster__c);
        AudienceUtils.audienceGroupCreation(new List<String>{audienceTest.ExternalId__c, audienceTest2.ExternalId__c}, audienceTest2.Cluster__c);
        
        //Return the same audiences created previously
        AudienceUtils.audienceGroupCreation(new List<String>{audienceTest.ExternalId__c}, audienceTest.Cluster__c);
        AudienceUtils.audienceGroupCreation(new List<String>{audienceTest2.ExternalId__c}, audienceTest2.Cluster__c);
        AudienceUtils.audienceGroupCreation(new List<String>{audienceTest2.ExternalId__c, audienceTest.ExternalId__c}, audienceTest2.Cluster__c);
        Test.stopTest();

        //Then
        System.assertEquals(3, [SELECT Id FROM Audience__c WHERE RecordTypeId =: AudienceUtils.rtAudienceGroup].size());
    }

    @isTest 
    static void audienceUserCalculation(){
        /* Comment: Checks if the method audienceUserCalculation calculates the Audiences that apply for a User based on the Audiences Criteria */

        //Given
        User u = [SELECT Id, Name FROM User WHERE Id =: UserInfo.getUserId()];
        Id clusterId = CMS.getUserSettings(UserInfo.getUserId()).Cluster__c;
        Audience__c audienceTest = [SELECT Id, Cluster__c, ExternalId__c FROM Audience__c WHERE Name = 'Test' AND RecordTypeId =: AudienceUtils.rtAudience];
        Audience__c audienceTest2 = [SELECT Id, Cluster__c, ExternalId__c FROM Audience__c WHERE Name = 'Test2' AND RecordTypeId =: AudienceUtils.rtAudience];
        Audience__c audienceTest3 = [SELECT Id, Cluster__c, ExternalId__c FROM Audience__c WHERE Name = 'Test3' AND RecordTypeId =: AudienceUtils.rtAudience];

        //When
        Test.startTest();
        CMS.updateUserSettings(u.Id, clusterId, null, null, null, u.Id);
        Test.stopTest();

        //Then
        System.assert(CMS.getUserAudiences(UserInfo.getUserId()).contains(audienceTest.ExternalId__c));
        System.assert(!CMS.getUserAudiences(UserInfo.getUserId()).contains(audienceTest2.ExternalId__c));
        System.assert(CMS.getUserAudiences(UserInfo.getUserId()).contains(audienceTest3.ExternalId__c));
    }

}