src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CMSUserSettings__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS User Settings</label>
    <nameField>
        <label>CMS User Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Users Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <description>Configure a new Menu component that has associated Menu records. They can be ordered manually.</description>
        <label>Menu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Represents menu options than can be related to other menu options.</description>
    <fields>
        <fullName>Audience__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Audience__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AudienceGroup</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Audience__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentMenu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>ParentMenus</relationshipLabel>
        <relationshipName>SubMenus</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <description>Represents the highest level of a Menu tree. It can be asociated to a component. (Ex. File)</description>
        <label>Menu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/MenuControllerTest.cls
@isTest
public class MenuControllerTest {
    @testSetup
    static void setup(){
        // Given in all cases
        MockupFactory.generateAcceleratorSetting();
        MockupFactory.createCluster('global', null, 1, 'ClusterRoot', 'CRT');
    }
    @isTest
    static void CASE_1(){
        //Comment: recuperar el ComponentWrapper de Navigation a partir de un ComponentExternalId, un ClasterId y un Device 
        //Given
        Cluster__c cluster = [SELECT id FROM Cluster__c LIMIT 1][0];
        List<Audience__c> audienceList = MockupFactory.createAudience('AudienceTest', 1, cluster.id);
        List<Component__c> component = MockupFactory.createComponent('Menu',1,cluster);
        List<RecordType> menuRTs = [SELECT Id FROM RecordType WHERE SObjectType =: GeneralUtils.prefix('[CMS]Menu__c') ORDER BY Name ASC];
        Menu__c mainMenu = MockupFactory.createMenu('mainMenu', 1, cluster.Id)[0]; 
        mainMenu.RecordTypeId = menuRTs[0].Id; update mainMenu;
        Menu__c subMenu1 = MockupFactory.createMenu('subMenu1', 1, cluster.Id)[0]; 
        subMenu1.RecordTypeId = menuRTs.get(1).Id; subMenu1.ParentMenu__c = mainMenu.Id; update subMenu1;
        Menu__c subMenu2 = MockupFactory.createMenu('subMenu2', 1, cluster.Id)[0]; 
        subMenu2.RecordTypeId = menuRTs.get(1).Id; subMenu2.ParentMenu__c = mainMenu.Id; update subMenu2;
        MenuAssignment__c menuAssignment = new MenuAssignment__c(component__c = component[0].Id, Menu__c=mainMenu.id);
        insert menuAssignment;
        
        List<Audience__c> audienceResultList =[SELECT id, ExternalId__c FROM Audience__c WHERE name like 'AudienceTest%'];
        AudienceManagerController.saveRelationships(mainMenu.id, GeneralUtils.prefix('[CMS]Menu__c'), new List<String>{audienceResultList[0].ExternalId__c}); 
        AudienceManagerController.saveRelationships(subMenu1.id, GeneralUtils.prefix('[CMS]Menu__c'), new List<String>{audienceResultList[0].ExternalId__c}); 
        AudienceManagerController.saveRelationships(subMenu2.id, GeneralUtils.prefix('[CMS]Menu__c'), new List<String>{audienceResultList[0].ExternalId__c}); 
        insert new CMSUserSettings__c(Name = UserInfo.getUserName(), User__c = UserInfo.getUserId(), Cluster__c = cluster.Id);


        //When
        test.startTest();
        MenuController.ComponentWrapper componentWrapper = MenuController.getNavWrapper(component[0].ExternalId__c, cluster.id, 'DESKTOP');
        test.stopTest();
        //Then
        System.assertNotEquals(null, componentWrapper);
        System.assertEquals(component[0].ExternalId__c, componentWrapper.component.ExternalId);
        System.assertEquals(cluster.id, componentWrapper.clusterId);
        System.assertEquals('DESKTOP', componentWrapper.device);
    }

    @isTest
    static void CASE_2(){
        //Comment: recuperar el ComponentWrapper de Navigation a partir de un ComponentExternalId, un ClasterId y un Device 
        //Given
        Cluster__c cluster = [SELECT id FROM Cluster__c LIMIT 1][0];
        List<Audience__c> audienceList = MockupFactory.createAudience('AudienceTest', 1, cluster.id);
        List<Component__c> component = MockupFactory.createComponent('Menu',1,cluster);
        List<RecordType> menuRTs = [SELECT Id FROM RecordType WHERE SObjectType =: GeneralUtils.prefix('[CMS]Menu__c') ORDER BY Name ASC];
        Menu__c mainMenu = MockupFactory.createMenu('mainMenu', 1, cluster.Id)[0]; 
        mainMenu.RecordTypeId = menuRTs[0].Id; update mainMenu;
        Menu__c subMenu1 = MockupFactory.createMenu('subMenu1', 1, cluster.Id)[0]; 
        subMenu1.RecordTypeId = menuRTs.get(1).Id; subMenu1.ParentMenu__c = mainMenu.Id; update subMenu1;
        Menu__c subMenu2 = MockupFactory.createMenu('subMenu2', 1, cluster.Id)[0]; 
        subMenu2.RecordTypeId = menuRTs.get(1).Id; subMenu2.ParentMenu__c = mainMenu.Id; update subMenu2;
        MenuAssignment__c menuAssignment = new MenuAssignment__c(component__c = component[0].Id, Menu__c=mainMenu.id);
        insert menuAssignment;
        
        List<Audience__c> audienceResultList =[SELECT id, ExternalId__c FROM Audience__c WHERE name like 'AudienceTest%'];
        AudienceManagerController.saveRelationships(mainMenu.id, GeneralUtils.prefix('[CMS]Menu__c'), new List<String>{audienceResultList[0].ExternalId__c}); 
        AudienceManagerController.saveRelationships(subMenu1.id, GeneralUtils.prefix('[CMS]Menu__c'), new List<String>{audienceResultList[0].ExternalId__c}); 
        AudienceManagerController.saveRelationships(subMenu2.id, GeneralUtils.prefix('[CMS]Menu__c'), new List<String>{audienceResultList[0].ExternalId__c}); 
        insert new CMSUserSettings__c(Name = UserInfo.getUserName(), User__c = UserInfo.getUserId(), Cluster__c = cluster.Id);

        List<Menu__c> allMenus= new List<Menu__c>{mainMenu,subMenu1,subMenu2};
        //When
        test.startTest();
        MenuController.NavWrapper componentWrapper = MenuController.getMenuWrapper(mainMenu.id, allMenus, new Set<String>{cluster.id});
        test.stopTest();
        //Then
        System.assertNotEquals(null, componentWrapper);
    }    
}