src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Represents menu options than can be related to other menu options.</description>
    <fields>
        <fullName>Audience__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Audience__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>AudienceGroup</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Audience__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AudienceManagerControllerTest.cls
@isTest 
public with sharing class AudienceManagerControllerTest {

	@isTest 
	static void menuRelatedToComponent() {

		// Given
		MockupFactory.generateAcceleratorSetting();
		List<Cluster__c> clusterList = MockupFactory.createCluster('Global', null, 1, 'ClusterRoot', 'CRT');
		List<Menu__c> menuList = MockupFactory.createMenu('testMenu', 2, clusterList[0].id);
		List<Audience__c> audienceList = MockupFactory.createAudience('testAudience', 1, clusterList[0].id);

		// When 
		Test.startTest();
		AudienceManagerController.RecordsWrapper record =  AudienceManagerController.getRecords(menuList[0].id, GeneralUtils.prefix('[CMS]Menu__c'));
		
		Test.stopTest();

		System.debug('DEBUG RECORD'+record);
		List<Audience__c> audienceResultList =[SELECT id, ExternalId__c FROM Audience__c WHERE name like 'testAudience%'];

		// Then
		System.assertEquals(record.recordsToSelect[0].externalId, audienceResultList[0].ExternalId__c);
	}


	@isTest 
	static void saveRelationshipsTest() {

		// Given
		MockupFactory.generateAcceleratorSetting();
		List<Cluster__c> clusterList = MockupFactory.createCluster('Global', null, 1, 'ClusterRoot', 'CRT');
		List<Menu__c> menuList = MockupFactory.createMenu('testMenu', 2, clusterList[0].id);
		List<Audience__c> audienceList = MockupFactory.createAudience('testAudience', 1, clusterList[0].id);

		List<Audience__c> audienceResultList =[SELECT id, ExternalId__c FROM Audience__c WHERE name like 'testAudience%'];

		// When 
		Test.startTest();
		String response = AudienceManagerController.saveRelationships(menuList[0].id, GeneralUtils.prefix('[CMS]Menu__c'), new List<String>{audienceResultList[0].ExternalId__c});
		Test.stopTest();

		// Then
		System.assertEquals('OK', response);
	}
	
}