src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <recordTypes>
        <fullName>Audience</fullName>
        <active>true</active>
        <description>Configure a new Audience to segment records.</description>
        <label>Audience</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ClusterRootExternalId__c</fullName>
        <formula>if(RecordType.DeveloperName = &apos;ClusterRoot&apos;, ExternalId__c, &apos;&apos;) 
+
if(ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, ParentCluster__r.ExternalId__c, &apos;&apos;) 
+ 
if(ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;) 
+ 
if(ParentCluster__r.ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, ParentCluster__r.ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster Root External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
	<fields>
        <fullName>BannerFrameType__c</fullName>
        <label>Banner Frame Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BannerFrameType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ButtonLabel__c</fullName>
        <label>Button Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Category</label>
        <referenceTo>Category__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClusterRootExternalId__c</fullName>
        <formula>if(Cluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ExternalId__c, &apos;&apos;)
+
if(Cluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)
+
if(Cluster__r.ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)
+
if(Cluster__r.ParentCluster__r.ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ParentCluster__r.ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster Root External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ContentRedirect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>NO RESPONDE A NUESTRO MODELO DE DATOS</description>
        <label>Content Redirect</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Content__c.RecordType.Name</field>
                <operation>equals</operation>
                <valueField>$Source.RedirectType__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Content__c</referenceTo>
        <relationshipLabel>Related Banners</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventDates__c</fullName>
        <formula>CASE(MONTH(DATEVALUE(EventStartDate__c)), 1,&apos;Jan&apos;, 2,&apos;Feb&apos;, 3,&apos;Mar&apos;, 4,&apos;Apr&apos;, 5,&apos;May&apos;, 6,&apos;Jun&apos;, 7,&apos;Jul&apos;, 8,&apos;Aug&apos;, 9,&apos;Sep&apos;, 10,&apos;Oct&apos;, 11,&apos;Nov&apos;, &apos;Dec&apos;)
 +&apos; &apos;+
 TEXT(DAY(DATEVALUE(EventStartDate__c)))
 +&apos;, &apos;+
 TEXT(YEAR(DATEVALUE(EventStartDate__c)))
 + 
 IF(EventStartDate__c != EventEndDate__c
 , &apos; - &apos; + 
 CASE(MONTH(DATEVALUE(EventEndDate__c)), 1,&apos;Jan&apos;, 2,&apos;Feb&apos;, 3,&apos;Mar&apos;, 4,&apos;Apr&apos;, 5,&apos;May&apos;, 6,&apos;Jun&apos;, 7,&apos;Jul&apos;, 8,&apos;Aug&apos;, 9,&apos;Sep&apos;, 10,&apos;Oct&apos;, 11,&apos;Nov&apos;, &apos;Dec&apos;)
 +&apos; &apos;+
 TEXT(DAY(DATEVALUE(EventEndDate__c)))
 +&apos;, &apos;+
 TEXT(YEAR(DATEVALUE(EventEndDate__c)))
 ,&apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Dates</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventEndDate__c</fullName>
        <label>Event End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventStartDate__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Event Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>EventStartDay__c</fullName>
        <formula>IF(DAY(DATEVALUE(EventStartDate__c)) &lt; 10, &apos;0&apos; &amp;  TEXT(DAY(DATEVALUE(EventStartDate__c))) , TEXT(DAY(DATEVALUE(EventStartDate__c))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Start Day</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EventStartMonth__c</fullName>
        <formula>CASE(
  MONTH(DATEVALUE( EventStartDate__c )),
  1, &quot;Jan&quot;,
  2, &quot;Feb&quot;,
  3, &quot;Mar&quot;,
  4, &quot;Apr&quot;,
  5, &quot;May&quot;,
  6, &quot;Jun&quot;,
  7, &quot;Jul&quot;,
  8, &quot;Aug&quot;,
  9, &quot;Sep&quot;,
  10, &quot;Oct&quot;,
  11, &quot;Nov&quot;,
  &quot;Dec&quot;
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Event Start Month</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Extract__c</fullName>
        <label>Extract</label>
        <length>1500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>HTMLContent__c</fullName>
        <inlineHelpText>If html content wants to be uploaded use this field instead of the Long Description one.</inlineHelpText>
        <label>HTML Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <formula>AND
(
 ISPICKVAL(Status__c,&apos;Active&apos;)
,OR
 (
  ISBLANK(PublishStartDate__c)
 ,PublishStartDate__c &lt; NOW()
 )
,OR
 (
  ISBLANK(PublishEndDate__c)
 ,PublishEndDate__c &gt; NOW()
 )
)</formula>
        <inlineHelpText>It is based on the Status and the Publish Dates</inlineHelpText>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies when a record represents a template</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Layout__c</fullName>
        <label>Layout</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Title Top</fullName>
                    <default>true</default>
                    <label>Title Top</label>
                </value>
                <value>
                    <fullName>Title Middle</fullName>
                </value>
                <value>
                    <fullName>Title Bottom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OverlayQuadrant__c</fullName>
        <label>Overlay Quadrant</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Top-Left</fullName>
                </value>
                <value>
                    <fullName>Top-Center</fullName>
                </value>
                <value>
                    <fullName>Top-Right</fullName>
                </value>
                <value>
                    <fullName>Middle-Left</fullName>
                </value>
                <value>
                    <fullName>Middle-Center</fullName>
                </value>
                <value>
                    <fullName>Middle-Right</fullName>
                </value>
                <value>
                    <fullName>Bottom-Left</fullName>
                </value>
                <value>
                    <fullName>Bottom-Center</fullName>
                </value>
                <value>
                    <fullName>Bottom-Right</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PublishEndDate__c</fullName>
        <label>Publish End Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PublishStartDate__c</fullName>
        <label>Publish Start Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PublishedDate__c</fullName>
        <description>NO RESPONDE A NUESTRO MODELO DE DATOS</description>
        <label>Actual Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>RedirectType__c</fullName>
        <label>Redirect Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Event</fullName>
                </value>
                <value>
                    <fullName>News</fullName>
                </value>
                <value>
                    <fullName>URL</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BannerFrameType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hero</fullName>
        <default>true</default>
        <label>Hero</label>
    </customValue>
    <customValue>
        <fullName>Page</fullName>
    </customValue>
    <customValue>
        <fullName>Square</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Banner Frame Type</masterLabel>
</GlobalValueSet>

src/classes/ObjectContentWrapper.cls
public class ObjectContentWrapper {
    
    public String Id;
    public String Name;
    public String RecordTypeId;
    public String RecordTypeName;
    public String RecordTypeDeveloperName;

    public Datetime PublishedDate;
    public String Audience;
    public String BannerFrameType;
    public String Body;
    public String ButtonLabel;
    public String Category;
    public String Cluster;
    public String ClusterRootExternalId;
    public String ContentRedirect;
    public String Description;
    public String EventDates;
    public Datetime EventEndDate;
    public Datetime EventStartDate;
    public String EventStartDay;
    public String EventStartMonth;
    public String ExternalId;
    public String Extract;
    public String HTMLContent;
    public Boolean IsActive;
    public Boolean IsTemplate;
    public String Layout;
    public String LinkDetail;
    public String Location;
    public Decimal Order;
    public String OverlayQuadrant;
    public Datetime PublishEndDate;
    public Datetime PublishStartDate;
    public String RedirectType;
    public String Status;
    public String StatusApprovalProcess;
    public String StructureComponent;
    public String StructureNavigation;
    public String TemplateDescription;
    public String TemplateUsed;
    public String Title;
    public String URLRedirect;

    public String LinkDetailURL;
    public String ClusterName;

    public List<MediaElementAssignment> MediaElementAssignments;

    public List<TagAssignment> Tags;

    public class MediaElementAssignment{
        public ObjectMediaElementWrapper MediaElement;
    }

    public class TagAssignment{
        public String tag;
        public String id;
    }
    
    public ObjectContentWrapper(Content__c content){
        try{this.Id = content.Id;}catch(Exception e){}
        try{this.Name = content.Name;}catch(Exception e){}
        try{this.RecordTypeId = content.RecordTypeId;}catch(Exception e){}
        try{this.RecordTypeName = content.RecordType.Name;}catch(Exception e){}
        try{this.RecordTypeDeveloperName = content.RecordType.DeveloperName;}catch(Exception e){}
        
        try{this.PublishedDate = content.PublishedDate__c;}catch(Exception e){}
        try{this.Audience = content.Audience__c;}catch(Exception e){}
        try{this.BannerFrameType = content.BannerFrameType__c;}catch(Exception e){}
        try{this.Body = content.Body__c;}catch(Exception e){}
        try{this.ButtonLabel = content.ButtonLabel__c;}catch(Exception e){}
        try{this.Category = content.Category__c;}catch(Exception e){}
        try{this.Cluster = content.Cluster__c;}catch(Exception e){}
        try{this.ClusterRootExternalId = content.ClusterRootExternalId__c;}catch(Exception e){}
        try{this.ContentRedirect = content.ContentRedirect__c;}catch(Exception e){}
        try{this.Description = content.Description__c;}catch(Exception e){}
        try{this.EventDates = content.EventDates__c;}catch(Exception e){}
        try{this.EventEndDate = content.EventEndDate__c;}catch(Exception e){}
        try{this.EventStartDate = content.EventStartDate__c;}catch(Exception e){}
        try{this.EventStartDay = content.EventStartDay__c;}catch(Exception e){}
        try{this.EventStartMonth = content.EventStartMonth__c;}catch(Exception e){}
        try{this.ExternalId = content.ExternalId__c;}catch(Exception e){}
        try{this.Extract = content.Extract__c;}catch(Exception e){}
        try{this.HTMLContent = content.HTMLContent__c;}catch(Exception e){}
        try{this.IsActive = content.IsActive__c;}catch(Exception e){}
        try{this.IsTemplate = content.IsTemplate__c;}catch(Exception e){}
        try{this.Layout = content.Layout__c;}catch(Exception e){}
        try{this.LinkDetail = content.LinkDetail__c;}catch(Exception e){}
        try{this.Location = content.Location__c;}catch(Exception e){}
        try{this.Order = content.Order__c;}catch(Exception e){}
        try{this.OverlayQuadrant = content.OverlayQuadrant__c;}catch(Exception e){}
        try{this.PublishEndDate = content.PublishEndDate__c;}catch(Exception e){}
        try{this.PublishStartDate = content.PublishStartDate__c;}catch(Exception e){}
        try{this.RedirectType = content.RedirectType__c;}catch(Exception e){}
        try{this.Status = content.Status__c;}catch(Exception e){}
        try{this.StatusApprovalProcess = content.StatusApprovalProcess__c;}catch(Exception e){}
        try{this.StructureComponent = content.StructureComponent__c;}catch(Exception e){}
        try{this.StructureNavigation = content.StructureNavigation__c;}catch(Exception e){}
        try{this.TemplateDescription = content.TemplateDescription__c;}catch(Exception e){}
        try{this.TemplateUsed = content.TemplateUsed__c;}catch(Exception e){}
        try{this.Title = content.Title__c;}catch(Exception e){}
        try{this.URLRedirect = content.URLRedirect__c;}catch(Exception e){}

        try{this.LinkDetailURL = content.LinkDetail__r.URL__c;}catch(Exception e){}
        try{this.ClusterName = content.Cluster__r.Name;}catch(Exception e){}

        //Media Element Assignment
        try{
            this.MediaElementAssignments = new List<MediaElementAssignment>();
            for(MediaElementAssignment__c mea: content.MediaElementAssignments__r){
                MediaElementAssignment meas = new MediaElementAssignment();
                meas.MediaElement = new ObjectMediaElementWrapper(mea.MediaElement__r);
                this.MediaElementAssignments.add(meas);
            }
        }catch(Exception e){}
        
        //Tag Assignment
        try{
            this.Tags= new List<TagAssignment>();
            for(TagAssignment__c taga: content.Tags__r){
                TagAssignment tagas = new TagAssignment();
                try{tagas.tag = taga.Tag__c;}catch(Exception e){}
                try{tagas.id = taga.Id;}catch(Exception e){}
                
                this.Tags.add(tagas);
            }
        }catch(Exception e){}
        
    }

    public Content__c parse(){
        Content__c content = new Content__c(Id = this.Id);
        try{content.Name = this.Name;}catch(Exception e){}
        try{content.RecordTypeId = this.RecordTypeId;}catch(Exception e){}
        
        try{content.PublishedDate__c = this.PublishedDate;}catch(Exception e){}
        try{content.Audience__c = this.Audience;}catch(Exception e){}
        try{content.BannerFrameType__c = this.BannerFrameType;}catch(Exception e){}
        try{content.Body__c = this.Body;}catch(Exception e){}
        try{content.ButtonLabel__c = this.ButtonLabel;}catch(Exception e){}
        try{content.Category__c = this.Category;}catch(Exception e){}
        try{content.Cluster__c = this.Cluster;}catch(Exception e){}
        try{content.ContentRedirect__c = this.ContentRedirect;}catch(Exception e){}
        try{content.Description__c = this.Description;}catch(Exception e){}
        try{content.EventEndDate__c = this.EventEndDate;}catch(Exception e){}
        try{content.EventStartDate__c = this.EventStartDate;}catch(Exception e){}
        try{content.ExternalId__c = this.ExternalId;}catch(Exception e){}
        try{content.Extract__c = this.Extract;}catch(Exception e){}
        try{content.HTMLContent__c = this.HTMLContent;}catch(Exception e){}
        try{content.IsTemplate__c = this.IsTemplate;}catch(Exception e){}
        try{content.Layout__c = this.Layout;}catch(Exception e){}
        try{content.LinkDetail__c = this.LinkDetail;}catch(Exception e){}
        try{content.Location__c = this.Location;}catch(Exception e){}
        try{content.Order__c = this.Order;}catch(Exception e){}
        try{content.OverlayQuadrant__c = this.OverlayQuadrant;}catch(Exception e){}
        try{content.PublishEndDate__c = this.PublishEndDate;}catch(Exception e){}
        try{content.PublishStartDate__c = this.PublishStartDate;}catch(Exception e){}
        try{content.RedirectType__c = this.RedirectType;}catch(Exception e){}
        try{content.Status__c = this.Status;}catch(Exception e){}
        try{content.StatusApprovalProcess__c = this.StatusApprovalProcess;}catch(Exception e){}
        try{content.StructureComponent__c = this.StructureComponent;}catch(Exception e){}
        try{content.StructureNavigation__c = this.StructureNavigation;}catch(Exception e){}
        try{content.TemplateDescription__c = this.TemplateDescription;}catch(Exception e){}
        try{content.TemplateUsed__c = this.TemplateUsed;}catch(Exception e){}
        try{content.Title__c = this.Title;}catch(Exception e){}
        try{content.URLRedirect__c = this.URLRedirect;}catch(Exception e){}
        return content;
    }

}