src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <recordTypes>
        <fullName>Audience</fullName>
        <active>true</active>
        <description>Configure a new Audience to segment records.</description>
        <label>Audience</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Behaviour__c</fullName>
        <label>Behaviour</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Tab</fullName>
                </value>
                <value>
                    <fullName>Same Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DefaultPage__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Default Page</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ParentNavigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Related Navigations</relationshipLabel>
        <relationshipName>RelatedNavigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URLMask__c</fullName>
        <label>URL Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <recordTypes>
        <fullName>Navigation</fullName>
        <active>true</active>
        <description>Internal or external navigation points. They are mostly references to community pages.</description>
        <label>Navigation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ObjectNavigationWrapper.cls
public class ObjectNavigationWrapper {
    
    @AuraEnabled public String Id;
    @AuraEnabled public String Name;
    @AuraEnabled public String RecordTypeId;
    @AuraEnabled public String RecordTypeName;
    @AuraEnabled public String RecordTypeDeveloperName;

    @AuraEnabled public String Audience;
	@AuraEnabled public String Behaviour;
	@AuraEnabled public String Cluster;
	@AuraEnabled public Boolean DefaultPage;
	@AuraEnabled public String Description;
	@AuraEnabled public String ExternalId;
	@AuraEnabled public String ParentNavigation;
	@AuraEnabled public String Status;
	@AuraEnabled public String Type;
	@AuraEnabled public String URL;
	@AuraEnabled public String URLMask;
    
    public ObjectNavigationWrapper(Navigation__c navigation){
        try{this.Id = navigation.Id;}catch(Exception e){}
        try{this.Name = navigation.Name;}catch(Exception e){}
        try{this.RecordTypeId = navigation.RecordTypeId;}catch(Exception e){}
        try{this.RecordTypeName = navigation.RecordType.Name;}catch(Exception e){}
        try{this.RecordTypeDeveloperName = navigation.RecordType.DeveloperName;}catch(Exception e){}
        
        try{this.Audience = navigation.Audience__c;}catch(Exception e){}
		try{this.Behaviour = navigation.Behaviour__c;}catch(Exception e){}
		try{this.Cluster = navigation.Cluster__c;}catch(Exception e){}
		try{this.DefaultPage = navigation.DefaultPage__c;}catch(Exception e){}
		try{this.Description = navigation.Description__c;}catch(Exception e){}
		try{this.ExternalId = navigation.ExternalId__c;}catch(Exception e){}
		try{this.ParentNavigation = navigation.ParentNavigation__c;}catch(Exception e){}
		try{this.Status = navigation.Status__c;}catch(Exception e){}
		try{this.Type = navigation.Type__c;}catch(Exception e){}
		try{this.URL = navigation.URL__c;}catch(Exception e){}
		try{this.URLMask = navigation.URLMask__c;}catch(Exception e){}
    }

}