src/objects/Audience__c.object
<CustomObject>
    <description>Represents the different Audience and Audience Group, which will be used for segment any record.</description>
    <fields>
        <fullName>AudienceCriteria__c</fullName>
        <label>Audience Criteria</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Audiences</relationshipLabel>
        <relationshipName>Audiences</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MatchCriteria__c</fullName>
        <inlineHelpText>Match Criteria governs how and when filters apply to your criteria. Use AND and OR operators to fine-tune your results.</inlineHelpText>
        <label>Match Criteria</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>All</fullName>
                </value>
                <value>
                    <fullName>Any</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ReferenceAudienceExternalIds__c</fullName>
        <label>Reference Audience External Ids</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ReferenceAudience__c</fullName>
        <label>Reference Audience</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <label>Audience</label>
    <nameField>
        <label>Audience Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audiences</pluralLabel>
    <recordTypes>
        <fullName>Audience</fullName>
        <active>true</active>
        <description>Configure a new Audience to segment records.</description>
        <label>Audience</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AudienceCriterion__c.object
<CustomObject>
    <fields>
        <fullName>Audience__c</fullName>
        <label>Audience</label>
        <referenceTo>Audience__c</referenceTo>
        <relationshipLabel>Audience Criteria</relationshipLabel>
        <relationshipName>AudienceCriteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <label>Field API Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MainObjectType__c</fullName>
        <label>Main Object Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>equals</fullName>
                </value>
                <value>
                    <fullName>not equals</fullName>
                </value>
                <value>
                    <fullName>greater than</fullName>
                </value>
                <value>
                    <fullName>greater or equal than</fullName>
                </value>
                <value>
                    <fullName>less than</fullName>
                </value>
                <value>
                    <fullName>less or equal than</fullName>
                </value>
                <value>
                    <fullName>contains</fullName>
                </value>
                <value>
                    <fullName>not contains</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ValueType__c</fullName>
        <label>Value Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Checkbox</fullName>
                </value>
                <value>
                    <fullName>Currency</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Number</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Lookup</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Audience Criterion</label>
    <nameField>
        <displayFormat>AC-{000000}</displayFormat>
        <label>Audience Criterion Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Audience Criteria</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterGroup</fullName>
        <active>true</active>
        <description>Represents a grouping cluster of other grouping clusters or cluster leafs. (Ex.: EMEA, Africa, Latam).</description>
        <label>Cluster Group</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/AudienceTriggersTest.cls
@isTest(seeAllData = false)
public class AudienceTriggersTest {
	
    @testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
	}

	@isTest
	static void setExternalId_Insert(){
		/* Comment: Checks if in the Audience__c creation the ExternalId__c is completed as required */

		//Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience);
		
		//When
		Test.startTest();
		insert audienceTest;
		Test.stopTest();

		//Then
		Audience__c audienceTestPost = [SELECT ExternalId__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertNotEquals(null, audienceTestPost.ExternalId__c);
	}

	@isTest 
	static void setExternalId_Update(){
		/* Comment: Checks if in the Audience__c update the ExternalId__c is completed as required */

		//Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience);
		insert audienceTest;

		//When
		Test.startTest();
		audienceTest.ExternalId__c = null;
        update audienceTest;
		Test.stopTest();

		//Then
		Audience__c audienceTestPost = [SELECT ExternalId__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertNotEquals(null, audienceTestPost.ExternalId__c);
	}

    @isTest
	static void setExternalIdAudienceGroup_Insert(){
		/* Comment: Checks if in the Audience__c creation the ExternalId__c is completed as required */

		//Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, RecordTypeId = AudienceUtils.rtAudienceGroup);
		
		//When
		Test.startTest();
		insert audienceTest;
		Test.stopTest();

		//Then
		Audience__c audienceTestPost = [SELECT ExternalId__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertNotEquals(null, audienceTestPost.ExternalId__c);
	}

    @isTest
	static void setExternalIdAudienceGroup_Update(){
		/* Comment: Checks if in the Audience__c update the ExternalId__c is completed as required */

		//Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, RecordTypeId = AudienceUtils.rtAudienceGroup);
		insert audienceTest;

		//When
		Test.startTest();
		audienceTest.ExternalId__c = null;
        update audienceTest;
		Test.stopTest();

		//Then
		Audience__c audienceTestPost = [SELECT ExternalId__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertNotEquals(null, audienceTestPost.ExternalId__c);
	}

    @isTest
	static void convertExternalIdsToSFIds(){
		/* Comment: Checks if the convertion of External Ids to SF Ids on Reference Audiences for Audience Groups works as required */

		//Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		
        Audience__c audienceTest1 = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test1', RecordTypeId = AudienceUtils.rtAudience);
        Audience__c audienceTest2 = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test2', RecordTypeId = AudienceUtils.rtAudience);
        insert new List<Audience__c>{audienceTest1, audienceTest2};
        List<Audience__c> audiencesTestList = [SELECT Id, ExternalId__c FROM Audience__c];

        Audience__c audienceTestGroup = new Audience__c(
            Cluster__c = clusterList[0].Id,
            Name = 'Test Group',
            RecordTypeId = AudienceUtils.rtAudienceGroup,
            ReferenceAudienceExternalIds__c = audiencesTestList[0].ExternalId__c + ';' + audiencesTestList[1].ExternalId__c
        );

		//When
		Test.startTest();
		insert audienceTestGroup;
		Test.stopTest();

		//Then
		Audience__c audienceTestGroupPost = [SELECT ReferenceAudience__c FROM Audience__c WHERE Id =: audienceTestGroup.Id];
        System.assertEquals(String.ValueOf(audiencesTestList[0].Id).substring(0, 15) + ';' + String.ValueOf(audiencesTestList[1].Id).substring(0, 15), audienceTestGroupPost.ReferenceAudience__c);
	}

    @isTest
	static void checkCustomCriteria(){
		/* Comment: Checks the validation of Audience Custom Criteria */

		//Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience);
		insert audienceTest;
		AudienceCriterion__c audCriterionTest1 = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'Account', Operator__c = 'equals', Order__c = 1, Value__c = 'Test', ValueType__c = 'Text');
        AudienceCriterion__c audCriterionTest2 = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'Account', Operator__c = 'equals', Order__c = 2, Value__c = 'Test', ValueType__c = 'Text');
        AudienceCriterion__c audCriterionTest3 = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'Account', Operator__c = 'equals', Order__c = 3, Value__c = 'Test', ValueType__c = 'Text');
        insert new List<AudienceCriterion__c>{audCriterionTest1, audCriterionTest2, audCriterionTest3};
		
        //When
		Test.startTest();
        List<String> errorMessages = new List<String>();
		audienceTest.MatchCriteria__c = 'Custom';
        audienceTest.AudienceCriteria__c = '1 OR (2 AND 4)';
        try{
            update audienceTest;
        }catch(DMLException e){
            errorMessages.add(e.getMessage());
        }
		audienceTest.AudienceCriteria__c = '1 A OR (2 AND 3)';
        try{
            update audienceTest;
        }catch(DMLException e){
            errorMessages.add(e.getMessage());
        }
		audienceTest.AudienceCriteria__c = '(1 OR (2 AND 3)';
        try{
            update audienceTest;
        }catch(DMLException e){
            errorMessages.add(e.getMessage());
        }
		audienceTest.AudienceCriteria__c = '1 OR (2 AND 3)';
		update audienceTest;
		Test.stopTest();

		//Then
		System.assertEquals(3, errorMessages.size());
		System.assert(errorMessages[0].contains(Label.CustomCriteriaValidation));
		System.assert(errorMessages[1].contains(Label.CustomCriteriaValidation));
		System.assert(errorMessages[2].contains(Label.CustomCriteriaValidation));
		Audience__c audienceTestPost = [SELECT AudienceCriteria__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertEquals('1 OR (2 AND 3)', audienceTestPost.AudienceCriteria__c);
	}

	@isTest
	static void checkCriteriaOnActivation(){
		/* Comment: Checks of validate activation of audience with criteria */

		//Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT');
        Cluster__c cg = clusterRootList[0];
        List<Cluster__c> clusterList = MockupFactory.createCluster('BuenosAires', cg.Id, 1, 'ClusterGroup', 'CGT');
		Audience__c audienceTest = new Audience__c(Cluster__c = clusterList[0].Id, Name = 'Test', RecordTypeId = AudienceUtils.rtAudience);
		insert audienceTest;
		
        //When
		Test.startTest();
		String errorMessage;
		audienceTest.Status__c = 'Active';
        try{
            update audienceTest;
        }catch(DMLException e){
            errorMessage = e.getMessage();
        }
		AudienceCriterion__c audCriterionTest1 = new AudienceCriterion__c(Audience__c = audienceTest.Id, FieldAPIName__c = 'Name', MainObjectType__c = 'Account', Operator__c = 'equals', Order__c = 1, Value__c = 'Test', ValueType__c = 'Text');
        insert new List<AudienceCriterion__c>{audCriterionTest1};
		audienceTest.Status__c = 'Active';
		update audienceTest;
		Test.stopTest();

		//Then
		System.assert(errorMessage.contains(Label.AudienceValidationOnStatusActivate));
		Audience__c audienceTestPost = [SELECT Status__c FROM Audience__c WHERE Id =: audienceTest.Id];
		System.assertEquals('Active', audienceTestPost.Status__c);
	}

}