src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CMSUserSettings__c.object
<CustomObject>
    <fields>
        <fullName>AudienceAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>AudienceContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Audience Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Audiences__c</fullName>
        <label>Audiences</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>CMS Users Settings</relationshipLabel>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomRecordId__c</fullName>
        <label>Custom Record Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CMSUsersSettings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>CMS User Settings</label>
    <nameField>
        <label>CMS User Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Users Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CMSUserSettingsUtils.cls
global with sharing class CMSUserSettingsUtils {
    
    //This methods updates the CMS User Settings with the audiences calculation
    global static void updateUserSettings(Id userId, Id clusterId, Id accountId, Id contactId, Id customRecordId){
        User user;
        try{user = [SELECT Id, UserName FROM User WHERE Id =: userId];}catch(Exception e){}
        

        if(user != null){
            if(Pattern.compile('[a-zA-Z0-9]{15}|[a-zA-Z0-9]{18}').matcher(String.valueOf(clusterId)).matches()){
                Schema.SObjectType sobjectType = clusterId.getSObjectType();
                String sobjectName = sobjectType.getDescribe().getName();
                
                if(GeneralUtils.prefix('[CMS]Cluster__c').equalsIgnoreCase(sobjectName)){
                    CMSUserSettings__c userSettings = getUserSettings(userId);
                    
                    //CMS User Settings creation
                    if(userSettings == null){
                        userSettings = new CMSUserSettings__c(
                            Name = user.UserName,
                            User__c = user.Id
                        );
                    }
                    userSettings.Cluster__c = clusterId;
                    userSettings.AudienceAccount__c = accountId;
                    userSettings.AudienceContact__c = contactId;
                    userSettings.CustomRecordId__c = customRecordId;

                    //Upsert CMS User Settings
                    upsert userSettings;

                    CMSUsersSettingsMap.put(user.Id, userSettings);
                }else{
                    throw new CMSException('CLUSTER_NOT_FOUND: ' + Label.ExceptionMessageClusterNotFound);
                }
            }else{
                throw new CMSException('CLUSTER_NOT_FOUND: ' + Label.ExceptionMessageClusterNotFound);
            }
        }else{
            throw new CMSException('USER_NOT_FOUND' + Label.ExceptionMessageUserNotFound);
        }
    }

    //This methods returns the CMS User Settings from a User Id
    private static Map<Id, CMSUserSettings__c> CMSUsersSettingsMap;
    global static CMSUserSettings__c getUserSettings(Id userId){
        if(CMSUsersSettingsMap == null){
            CMSUsersSettingsMap = new Map<Id, CMSUserSettings__c>();
        }
        if(!CMSUsersSettingsMap.containsKey(userId)){
            try{CMSUsersSettingsMap.put(userId, [SELECT Id, User__c, Cluster__c, Audiences__c FROM CMSUserSettings__c WHERE User__c =: userId]);}catch(Exception e){}
        }
        
        return CMSUsersSettingsMap.get(userId);
    }

    //This methods returns a set of Audiences External Ids of a User
    global static Set<String> getUserAudiences(Id userId){
        Set<String> userAudiencesSet = new Set<String>();
        if(getUserSettings(userId).Audiences__c != null){
            userAudiencesSet.addAll(getUserSettings(userId).Audiences__c.split(';'));
        }
        return userAudiencesSet;
    }
}