src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>NumberOfColumns__c</fullName>
        <description>Use this field to define the number of columns to show.</description>
        <inlineHelpText>Use this field to define the number of columns to show.</inlineHelpText>
        <label>Number of Columns</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <label>Order By</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Datasource__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CreatedDate ASC</fullName>
                    <default>true</default>
                    <label>Creation Date ASC</label>
                </value>
                <value>
                    <fullName>CreatedDate DESC</fullName>
                    <label>Creation Date DESC</label>
                </value>
                <value>
                    <fullName>Name ASC</fullName>
                </value>
                <value>
                    <fullName>Name DESC</fullName>
                </value>
                <value>
                    <fullName>Category__r.Name ASC</fullName>
                    <label>Category ASC</label>
                </value>
                <value>
                    <fullName>Category__r.Name DESC</fullName>
                    <label>Category DESC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c ASC</fullName>
                    <label>Publish Start Date ASC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c DESC</fullName>
                    <label>Publish Start Date DESC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c ASC</fullName>
                    <label>Event Start Date ASC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c DESC</fullName>
                    <label>Event Start Date DESC</label>
                </value>
                <value>
                    <fullName>Title__c ASC</fullName>
                    <label>Title ASC</label>
                </value>
                <value>
                    <fullName>Title__c DESC</fullName>
                    <label>Title DESC</label>
                </value>
                <value>
                    <fullName>Custom Sorting</fullName>
                </value>
                <value>
                    <fullName>Manual Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Datatables</relationshipLabel>
        <relationshipName>ListViews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipName>LisViews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NumberOfColumns__c</fullName>
        <label>Number of Columns</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ObjectApiName__c</fullName>
        <label>Object Api Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <inlineHelpText>The value on this field set up how the records will be ordered and display in the frontend.</inlineHelpText>
        <label>Order by</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordsPerPage__c</fullName>
        <label>Records Per Page</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>WhereCondition__c</fullName>
        <label>Where Condition</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DatatableAction__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datatable__c</fullName>
        <label>Datatable</label>
        <referenceTo>Datatable__c</referenceTo>
        <relationshipLabel>Datatable Actions</relationshipLabel>
        <relationshipName>DatatableActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DisplaySettings__c</fullName>
        <label>Display Settings</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Desktop</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <label>Label</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Datatable Actions</relationshipLabel>
        <relationshipName>DatatableActions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Navigation</fullName>
                </value>
                <value>
                    <fullName>Custom</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Datatable Action</label>
    <nameField>
        <label>Datatable Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatable Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Internal</fullName>
                </value>
                <value>
                    <fullName>External</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FE_DatatableUtilsTest.cls
@isTest
public class FE_DatatableUtilsTest {
    @testSetup
    static void generateCustomSettings(){
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'DRC');
        List<Datatable__c> datatableList = MockupFactory.createDatatables('Table Test', 'TableTest', 'Component__c', 1, clusterRootList[0].Id);
        
        System.debug('datatableExternalId: ' + datatableList.get(0).ExternalId__c);
        
    	List<DatatableElement__c> dataElementList = MockupFactory.createDatatableElements('Name', 'DataElementExternalId', 2, datatableList[0].Id);
    }
    
	@isTest
    public static void processSearchTermTest01() {
        Test.startTest();
        Datatable__c datatable = FE_DatatableUtils.getDatatableInfo('TableTest_0');
        
        datatable.NumberOfColumns__c = '10';
        update datatable;
        
        List<DatatableElement__c> elems = new List<DatatableElement__c>();
        DatatableElement__c ele = new DatatableElement__c();
        ele.Name = 'DatatableElementTest1';
        ele.Searchable__c = true;
        ele.FieldApiName__c = 'Name';
        ele.Datatable__c = datatable.Id;
        ele.Label__c = 'Name';
        
        elems.add(ele);
        insert elems;
        
        datatable = FE_DatatableUtils.getDatatableInfo('TableTest_0');
        
        String searchTerm = 'test';
            
        FE_DatatableUtils.processSearchTerm(datatable, searchTerm);
        
        Test.stopTest();
    }
    
    @isTest
    public static void doGetRecordsTest() {
        Test.startTest();
        
        Cluster__c clus = MockupFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot', 'DummyCluster').get(0);
        
        Datatable__c datatable = new Datatable__c();
        datatable.Name = 'DummyDatatable';
        datatable.ObjectApiName__c = 'User';
        
        datatable.Cluster__c = clus.Id;
        datatable.RecordsPerPage__c = 2;
        datatable.NumberOfColumns__c = '2';
        datatable.OrderBy__c = 'Name ASC';
        datatable.WhereCondition__c = 'WHERE Name != null';
        insert datatable;
        
        DatatableElement__c elem = new DatatableElement__c();
        elem.Name = 'DummyDatatableElement';
        elem.Datatable__c = datatable.Id;
        elem.FieldApiName__c = 'CreatedDate';
        elem.Label__c = 'Created Date'; 
        
        insert elem;
        
        Datatable__c d = [SELECT Id, WhereCondition__c, ObjectApiName__c, OrderBy__c
                          		, RecordsPerPage__c
                          		, (SELECT Id, FieldApiName__c, Navigation__c FROM DatatableElements__r) 
                          	FROM Datatable__c WHERE Name = 'DummyDatatable'];
        FE_DatatableController.DatatableWrapper wrapper = new FE_DatatableController.DatatableWrapper();
        
        FE_DatatableUtils.doGetRecords(d, 0, wrapper);
        
        Test.stopTest();
    }
    
    @isTest
    public static void mapDatatableDataToWrappersTest() {
        Test.startTest();
        
        Cluster__c clus = MockupFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot', 'DummyCluster').get(0);
        
        Datatable__c datatable = new Datatable__c();
        datatable.Name = 'DummyDatatable';
        datatable.ObjectApiName__c = 'User';
        
        datatable.Cluster__c = clus.Id;
        datatable.RecordsPerPage__c = 2;
        datatable.NumberOfColumns__c = '2';
        datatable.OrderBy__c = 'Name ASC';
        datatable.WhereCondition__c = 'WHERE Name != null';
        insert datatable;
        
        DatatableElement__c elem = new DatatableElement__c();
        elem.Name = 'DummyDatatableElement';
        elem.Datatable__c = datatable.Id;
        elem.FieldApiName__c = 'CreatedDate';
        elem.Label__c = 'Created Date';
        elem.DisplaySettings__c = 'Both';
        
        insert elem;
        
        elem = new DatatableElement__c();
        elem.Name = 'DummyDatatableElement2';
        elem.Datatable__c = datatable.Id;
        elem.FieldApiName__c = 'DigestFrequency';
        elem.Label__c = 'DigestFrequency';
        elem.DisplaySettings__c = 'Both';
        
        insert elem;
        
        List<User> users = [SELECT Id, Username, CreatedDate, DigestFrequency FROM User];
        
        System.debug('users: ' + users);
        
        Datatable__c d = [SELECT Id, WhereCondition__c, ObjectApiName__c, OrderBy__c
                          		, RecordsPerPage__c
                          		, (SELECT Id, FieldApiName__c, Label__c, Type__c, ColumnInformation__c
                                   		, DisplaySettings__c, Searchable__c, Filtrable__c, Sortable__c
                                   		, Navigation__c, ExcludedPicklistValues__c
                                   		, Datatable__c, Datatable__r.ObjectApiName__c
                                   	FROM DatatableElements__r) 
                          	FROM Datatable__c WHERE Name = 'DummyDatatable'];
        
        List<FE_DatatableController.DatatableElementWrapper> elems = FE_DatatableUtils.mapDatatableElementsToWrappers(d.DatatableElements__r);
        FE_DatatableUtils.mapDatatableDataToWrappers(users, elems);
        
        Test.stopTest();
    }
    
    @isTest
    public static void getDatatableInfoTest01() {
        
        Test.startTest();
        
        Datatable__c dat = FE_DatatableUtils.getDatatableInfo('TableTest_0');
        FE_DatatableController.DatatableWrapper dw = FE_DatatableUtils.mapDatatableToWrapper(dat);
        
        Test.stopTest();
    }
        
    @isTest
    public static void mapDatatableActionsToWrappersTest01() {
        Test.startTest();
        
        List<DatatableAction__c> actions = new List<DatatableAction__c>();
        
        List<FE_DatatableController.DatatableActionWrapper> daw = FE_DatatableUtils.mapDatatableActionsToWrappers(actions);
        
        Test.stopTest();
    }
    
    @isTest
    public static void processAppliedFiltersTest01() {
        Test.startTest();
        
        List<FE_DatatableController.DatatableFilterWrapper> appliedFilters = new List<FE_DatatableController.DatatableFilterWrapper>();
        FE_DatatableController.DatatableFilterFieldWrapper filt;
        FE_DatatableController.DatatableFilterWrapper af;
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value1 = 'aloha';
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'Name';
        filt.type = String.valueOf(Schema.DisplayType.STRING);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value1 = String.valueOf(Datetime.now());
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'CreatedDate';
        filt.type = String.valueOf(Schema.DisplayType.DATETIME);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value1 = String.valueOf(5);
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'NumbOfDays__c';
        filt.type = String.valueOf(Schema.DisplayType.INTEGER);
        af.filter = filt;
        
        appliedFilters.add(af);
        
            
        FE_DatatableUtils.processAppliedFilters(appliedFilters);
        
        Test.stopTest();
    }
    
    @isTest
    public static void processAppliedFiltersTest02() {
        Test.startTest();
        
        List<FE_DatatableController.DatatableFilterWrapper> appliedFilters = new List<FE_DatatableController.DatatableFilterWrapper>();
        FE_DatatableController.DatatableFilterFieldWrapper filt;
        FE_DatatableController.DatatableFilterWrapper af;
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value1 = 'aloha';
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'Name';
        filt.type = String.valueOf(Schema.DisplayType.STRING);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value1 = String.valueOf(Datetime.now());
        af.value2 = String.valueOf(Datetime.now());
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'CreatedDate';
        filt.type = String.valueOf(Schema.DisplayType.DATETIME);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value1 = String.valueOf(5);
        af.value2 = String.valueOf(8);
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'NumbOfDays__c';
        filt.type = String.valueOf(Schema.DisplayType.INTEGER);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        FE_DatatableUtils.processAppliedFilters(appliedFilters);
        
        Test.stopTest();
    }
    
    @isTest
    public static void processAppliedFiltersTest03() {
        Test.startTest();
        
        List<FE_DatatableController.DatatableFilterWrapper> appliedFilters = new List<FE_DatatableController.DatatableFilterWrapper>();
        FE_DatatableController.DatatableFilterFieldWrapper filt;
        FE_DatatableController.DatatableFilterWrapper af;
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value1 = 'aloha';
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'Name';
        filt.type = String.valueOf(Schema.DisplayType.STRING);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value2 = String.valueOf(Datetime.now());
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'CreatedDate';
        filt.type = String.valueOf(Schema.DisplayType.DATETIME);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        af = new FE_DatatableController.DatatableFilterWrapper();
        af.value2 = String.valueOf(5);
        filt = new FE_DatatableController.DatatableFilterFieldWrapper();
        filt.name = 'NumbOfDays__c';
        filt.type = String.valueOf(Schema.DisplayType.INTEGER);
        af.filter = filt;
        
        appliedFilters.add(af);
        
        FE_DatatableUtils.processAppliedFilters(appliedFilters);
        
        Test.stopTest();
    }

}