src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/NavigationTriggersTest.cls
@isTest
private class NavigationTriggersTest
{

	@testSetup
	static void generateCustomSettings(){
		MockupFactory.generateAcceleratorSetting();
	}
	
	@isTest
	static void insertNavigationSharing()
	{
		

		// Given
		//List<String> clustersList = new List<String>();
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'CRT');
		List<Cluster__c> clusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 1 ];
		
		// When
		Test.startTest();
		List<Navigation__c> tagList = MockupFactory.createNavigation('navTest1', 'Url.com', 1,clusterList[0].Id);
		
		Test.stopTest();
		
		// Then
		List<Navigation__Share> shareList = [SELECT Id, ParentId FROM Navigation__Share WHERE ParentId = :tagList[0].Id AND RowCause =: GeneralUtils.prefix('[CMS]Clustering__c')];
		
		System.assertEquals(3, shareList.size());

	}

	@isTest
	static void insertNavigationSharingWithoutClusterId()
	{
		

		// Given
		//List<String> clustersList = new List<String>();
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'CRT');
		List<Cluster__c> clusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 1 ];
		
		// When
		Test.startTest();
		List<Navigation__c> tagList = MockupFactory.createNavigation('navTest1', 'Url.com', 1,null);
		
		Test.stopTest();
		
		// Then
		List<Navigation__Share> shareList = [SELECT Id, ParentId FROM Navigation__Share WHERE ParentId = :tagList[0].Id AND RowCause =: GeneralUtils.prefix('[CMS]Clustering__c')];
		
		System.assertEquals(0, shareList.size());

	}

	@isTest
	static void updateNavigationSharing()
	{
		

		// Given
		//List<String> clustersList = new List<String>();
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 2, 'ClusterRoot', 'CRT');
		List<Cluster__c> getClusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 2 ];
		
		List<Navigation__c> navList = MockupFactory.createNavigation('navTest1', 'Url.com', 1,getClusterList[0].Id);
		List<Navigation__c> getNavList = [SELECT Id, Name FROM Navigation__c WHERE Name LIKE 'navTest1%'];
		
		Navigation__c getNavToUpdate = getNavList[0];
		getNavToUpdate.Cluster__c = getClusterList[1].Id;
		List<Navigation__c> navigationToInsert = new List<Navigation__c>{getNavToUpdate};
		// When
		Test.startTest();
		update navigationToInsert;
		Test.stopTest();

		// Then
		List<Navigation__Share> shareList = [SELECT Id, ParentId FROM Navigation__Share WHERE ParentId = :navigationToInsert[0].Id AND RowCause =: GeneralUtils.prefix('[CMS]Clustering__c')];
		
		System.assertEquals(6, shareList.size());

	}

	@isTest
	static void updateNavigationSharingWithoutClusterId()
	{
		

		// Given
		//List<String> clustersList = new List<String>();
		List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 2, 'ClusterRoot', 'CRT');
		List<Cluster__c> getClusterList = [SELECT Id, Name FROM Cluster__c WHERE Name LIKE 'ClusterRootTest%' LIMIT 2 ];
		
		List<Navigation__c> navList = MockupFactory.createNavigation('navTest1', 'Url.com', 1,getClusterList[0].Id);
		List<Navigation__c> getNavList = [SELECT Id, Name FROM Navigation__c WHERE Name LIKE 'navTest1%'];
		
		Navigation__c getNavToUpdate = getNavList[0];
		getNavToUpdate.Cluster__c = getClusterList[0].Id;
		List<Navigation__c> navigationToInsert = new List<Navigation__c>{getNavToUpdate};
		// When
		Test.startTest();
		update navigationToInsert;
		Test.stopTest();

		// Then
		List<Navigation__Share> shareList = [SELECT Id, ParentId FROM Navigation__Share WHERE ParentId = :navigationToInsert[0].Id AND RowCause =: GeneralUtils.prefix('[CMS]Clustering__c')];
		
		System.assertEquals(3, shareList.size());

	}

}