src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FormValidation__c.object
<CustomObject>
    <description>Object that represents a validation that is executed on a Community Form</description>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Form Validation</label>
    <nameField>
        <label>Form Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/FormValidationTriggersTest.cls
@isTest(seeAllData = false)
public class FormValidationTriggersTest {
	
	@isTest 
	static void insertFormValidationTest(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        Cluster__c cluster = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT')[0];
		//When
		Test.startTest();
		MockupFactory.createForm('testName', 'testName', 'testRetrieval', cluster.id);		
		Test.stopTest();
		//Then
		FormValidation__c formValidation = [SELECT id, ExternalId__c FROM FormValidation__c LIMIT 1];
        System.assert(formValidation.ExternalId__c != null);

	}

	@isTest
	static void updateFormValidation(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        Cluster__c cluster = MockupFactory.createCluster('Argentina', null, 2, 'ClusterRoot', 'CRT')[0];
        MockupFactory.createForm('testName', 'testName', 'testRetrieval', cluster.id);
		//When
		Test.startTest();
		FormValidation__c formValidation = [SELECT id, name FROM FormValidation__c LIMIT 1];
        formValidation.name = 'updated';
        update formValidation;
        Test.stopTest();
		//Then
		formValidation = [SELECT id, ExternalId__c FROM FormValidation__c LIMIT 1];
        System.assert(formValidation.ExternalId__c != null);

	}
}