src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Content Assignment</relationshipLabel>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BE_TagCriteriaManagerControllerTest.cls
@isTest 
public with sharing class BE_TagCriteriaManagerControllerTest {

@isTest 
    static void getTagsFromComponentTest(){
        //Given
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> cluster = MockupFactory.createCluster('Global',null, 1,'ClusterRoot');
        List<Component__c> comp = MockupFactory.createComponent('Banner', 1);
        List<Content__c> cont = MockupFactory.createContent('Banner',cluster[0],1);
        List<Tag__c> tags = MockupFactory.createTag('TestTag','TestDescription',1,cluster[0].Id);
        List<TagAssignment__c> tagsAss = MockupFactory.createTagAssignment(tags,comp,cont);

        //List<ContentAssignment__c> contAssign = MockupFactory.createContentAssignment(cont,comp);

        //When 
        Test.startTest();
        BE_TagCriteriaManagerController.RecordsWrapper rw = BE_TagCriteriaManagerController.getRecords(comp[0].Id);
        Test.stopTest();

        //Then    
        System.assertNotEquals(null, rw.recordsToSelect);
    }

    @isTest 
    static void saveTagsWithValidFormulaAndCriteriaTest() {

        // Given
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> cluster = MockupFactory.createCluster('Global', null, 1, 'ClusterRoot');
        List<Component__c> comp = MockupFactory.createComponent('Banner', 1);
        List<Tag__c> tags = MockupFactory.createTag('TestTag','TestDescription',2,cluster[0].Id);
        List<String> listSelectedIds = new List<String>(); 
        listSelectedIds.add(tags[0].Id);
        listSelectedIds.add(tags[1].Id);

        // When 
        Test.startTest();
        String response = BE_TagCriteriaManagerController.saveRelationships(comp[0].Id, listSelectedIds, 'ANY', '1 AND 2');
        Test.stopTest();

        // Then
        System.assertEquals('OK', response);
    }

    @isTest 
    static void saveTagsWithInvalidFormulaTest() {

        // Given
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> cluster = MockupFactory.createCluster('Global', null, 1, 'ClusterRoot');
        List<Component__c> comp = MockupFactory.createComponent('Banner', 1);
        List<Tag__c> tags = MockupFactory.createTag('TestTag','TestDescription',2,cluster[0].Id);
        List<String> listSelectedIds = new List<String>(); 
        listSelectedIds.add(tags[0].Id);
        listSelectedIds.add(tags[1].Id);

        // When 
        Test.startTest();
        String response = BE_TagCriteriaManagerController.saveRelationships(comp[0].Id, listSelectedIds, 'ANY', '1 AD');
        Test.stopTest();

        // Then
        System.assertNotEquals('OK', response);
    }

    @isTest 
    static void saveNoTagsSelectedWithNoCriteriaTest() {

        // Given
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> cluster = MockupFactory.createCluster('Global', null, 1, 'ClusterRoot');
        List<Component__c> comp = MockupFactory.createComponent('Banner', 1);
        List<Tag__c> tags = MockupFactory.createTag('TestTag','TestDescription',3,cluster[0].Id);
        List<String> listSelectedIds = new List<String>(); 

        // When 
        Test.startTest();
        String response = BE_TagCriteriaManagerController.saveRelationships(comp[0].Id, listSelectedIds, 'ANY', '');
        Test.stopTest();

        // Then
        System.assertEquals('OK', response);
    }

    @isTest 
    static void saveTagsSelectedWithNoCriteriaTest() {

        // Given
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> cluster = MockupFactory.createCluster('Global', null, 1, 'ClusterRoot');
        List<Component__c> comp = MockupFactory.createComponent('Banner', 1);
        List<Tag__c> tags = MockupFactory.createTag('TestTag','TestDescription',3,cluster[0].Id);

        List<String> listSelectedIds = new List<String>(); 
        listSelectedIds.add(tags[0].Id);
        listSelectedIds.add(tags[1].Id);

        // When 
        Test.startTest();
        String response = BE_TagCriteriaManagerController.saveRelationships(comp[0].Id, listSelectedIds, 'ANY', '');
        Test.stopTest();

        // Then
        System.assertEquals(Label.CriteriaListInBlank, response);
    }
    
    @isTest 
    static void getSelectedRecordsTest() {

        // Given
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> cluster = MockupFactory.createCluster('Global', null, 1, 'ClusterRoot');
        List<Component__c> comp = MockupFactory.createComponent('Banner', 1);
        List<Tag__c> tags = MockupFactory.createTag('TestTag','TestDescription',3,cluster[0].Id);

        List<String> listSelectedIds = new List<String>(); 
        listSelectedIds.add(tags[0].Id);
        listSelectedIds.add(tags[1].Id);
        BE_TagCriteriaManagerController.RecordsWrapper rw = BE_TagCriteriaManagerController.getRecords(comp[0].Id);

        // When
        Test.startTest();
        BE_TagCriteriaManagerController.RecordsWrapper response = BE_TagCriteriaManagerController.getSelectedRecords(JSON.serialize(rw), listSelectedIds);
        Test.stopTest();

        // Then
        System.assertEquals(2, response.recordsSelected.size());
    }
}