src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Datatables</relationshipLabel>
        <relationshipName>ListViews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/DatatableAction__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <label>Component</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Datatable__c</fullName>
        <label>Datatable</label>
        <referenceTo>Datatable__c</referenceTo>
        <relationshipLabel>Datatable Actions</relationshipLabel>
        <relationshipName>DatatableActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Datatable Action</label>
    <nameField>
        <label>Datatable Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatable Actions</pluralLabel>
    <recordTypes>
        <fullName>RowAction</fullName>
        <active>true</active>
        <label>Row Action</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FE_DatatableControllerTest.cls
@isTest
public class FE_DatatableControllerTest {
    
    @testSetup
    static void generateCustomSettings(){
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'DRC');
        List<Datatable__c> datatableList = MockupFactory.createDatatables('Table Test', 'TableTest', 'Component__c', 1, clusterRootList[0].Id);
    	List<DatatableElement__c> dataElementList = MockupFactory.createDatatableElements('Name', 'DataElementExternalId', 2, datatableList[0].Id);
    }
    
    @isTest
    static void testDoInit(){       
        // Given
		Datatable__c data = [Select ExternalId__c from Datatable__c where ExternalId__c like'TableTest%' Limit 1];
        // When
        Test.startTest();
        String jsonTest = FE_DatatableController.doInit(data.ExternalId__c);
        Test.stopTest();
        // Then
        System.assertNotEquals(jsonTest, null);
    }
    
    @isTest
    static void testGetPage(){     
        // Given
        Datatable__c data = [Select ExternalId__c from Datatable__c where ExternalId__c like'TableTest%' Limit 1];
        
        FE_DatatableController.DatatableWrapper jsonWrapper = new FE_DatatableController.DatatableWrapper();
        jsonWrapper.componentExternalId = data.ExternalId__c;
        jsonWrapper.pagingType = 'Bottom';
        jsonWrapper.numberOfColumns = 3;
        jsonWrapper.recordsPerPage = 2;

        // When
        Test.startTest();        
        String jsonTest = FE_DatatableController.getPage(JSON.serialize(jsonWrapper),1);
        Test.stopTest();
        
        // Then
        System.assertNotEquals(jsonTest, null);
    }
    
    @isTest
    static void testHandleDelete(){       
       // Given
        Datatable__c data = [Select ExternalId__c from Datatable__c where ExternalId__c like'TableTest%' Limit 1];
        String jsonComponentWrapper = FE_DatatableController.doInit(data.ExternalId__c);
        // When
        Test.startTest();
       	List<Id> ids=new List<Id>();
        String jsonTest = FE_DatatableController.handleDelete(jsonComponentWrapper, ids);
        Test.stopTest();
        // Then
        System.assertEquals(jsonTest, '');
    }
    
    @isTest
    static void testhandleFilter(){
       // Given
        Datatable__c data = [Select ExternalId__c from Datatable__c where ExternalId__c like'TableTest%' Limit 1];

        FE_DatatableController.DatatableWrapper jsonWrapper = new FE_DatatableController.DatatableWrapper();
        jsonWrapper.componentExternalId = data.ExternalId__c;
        jsonWrapper.pagingType = 'Bottom';
        jsonWrapper.numberOfColumns = 3;
        jsonWrapper.recordsPerPage = 2;
		
        jsonWrapper.name ='Test';
        jsonWrapper.totalRows = 1;
        FE_DatatableController.DatatableRowWrapper row = new FE_DatatableController.DatatableRowWrapper();
        row.columnName = 'Name column test';
        row.rowValue = 'test value';
        List<FE_DatatableController.DatatableRowWrapper> rowList = new List<FE_DatatableController.DatatableRowWrapper>();
        rowList.add(row);
        jsonWrapper.tableData = new List<Map<String, String>>();
        //jsonWrapper.tableData.add(rowList);
             
        // When
        Test.startTest();
        String jsonTest = FE_DatatableController.handleFilter(JSON.serialize(jsonWrapper));
        Test.stopTest();
        // Then
        System.assertNotEquals(jsonTest, null);
    }

	@isTest
    static void testhandleSort(){ 
	
     // Given
        Datatable__c data = [Select ExternalId__c from Datatable__c where ExternalId__c like'TableTest%' Limit 1];
        
        FE_DatatableController.DatatableWrapper jsonWrapper = new FE_DatatableController.DatatableWrapper();
        jsonWrapper.componentExternalId = data.ExternalId__c;
        jsonWrapper.pagingType = 'Bottom';
        jsonWrapper.numberOfColumns = 3;
        jsonWrapper.recordsPerPage = 2;
        
        // When   
        Test.startTest();
       	
        String jsonTest = FE_DatatableController.handleSort(JSON.serialize(jsonWrapper), 'Name', 'ASC');
        Test.stopTest();
        // Then
        System.assertNotEquals(jsonTest, null);
    }

	@isTest
    static void TestprocessAppliedFilters(){   
        
        //Given
        FE_DatatableController.DatatableFilterFieldWrapper filterFieldWrStr = new FE_DatatableController.DatatableFilterFieldWrapper(); 
        filterFieldWrStr.name='TestFilterField';
        filterFieldWrStr.type='String';
        FE_DatatableController.DatatableFilterWrapper dataFilterWrStr =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrStr.filter=filterFieldWrStr;
        dataFilterWrStr.value1 = 'test';
        dataFilterWrStr.value2 = 'table';
        
        FE_DatatableController.DatatableFilterFieldWrapper filterFieldWrInt = new FE_DatatableController.DatatableFilterFieldWrapper(); 
        filterFieldWrInt.name='TestFilterField';
        filterFieldWrInt.type='Integer';    
        FE_DatatableController.DatatableFilterWrapper dataFilterWrInt =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrInt.filter=filterFieldWrInt;
        dataFilterWrInt.value1 = '123';
        dataFilterWrInt.value2 = '890';
        FE_DatatableController.DatatableFilterWrapper dataFilterWrIntV1 =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrIntV1.filter=filterFieldWrInt;
        dataFilterWrIntV1.value1 = '123';
        dataFilterWrIntV1.value2 = null;  
        FE_DatatableController.DatatableFilterWrapper dataFilterWrIntV2 =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrIntV2.filter=filterFieldWrInt;
        dataFilterWrIntV2.value1 = null;
        dataFilterWrIntV2.value2 = '890';
        
        FE_DatatableController.DatatableFilterFieldWrapper filterFieldWrDouble = new FE_DatatableController.DatatableFilterFieldWrapper(); 
        filterFieldWrDouble.name='TestFilterField';
        filterFieldWrDouble.type='Double';
        FE_DatatableController.DatatableFilterWrapper dataFilterWrDouble =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrDouble.filter=filterFieldWrDouble;
        dataFilterWrDouble.value1 = null;
        dataFilterWrDouble.value2 = '890.5';

        FE_DatatableController.DatatableFilterFieldWrapper filterFieldWrDate = new FE_DatatableController.DatatableFilterFieldWrapper(); 
        filterFieldWrDate.name='TestFilterField';
        filterFieldWrDate.type='Date';    
        FE_DatatableController.DatatableFilterWrapper dataFilterWrDate =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrDate.filter=filterFieldWrDate;
        dataFilterWrDate.value1 = '2019-03-28';
        dataFilterWrDate.value2 = '2019-03-29';
        FE_DatatableController.DatatableFilterWrapper dataFilterWrDateV1 =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrDateV1.filter=filterFieldWrDate;
        dataFilterWrDateV1.value1 = null;
        dataFilterWrDateV1.value2 = '2019-03-29';
        FE_DatatableController.DatatableFilterWrapper dataFilterWrDateV2 =new FE_DatatableController.DatatableFilterWrapper();
        dataFilterWrDateV2.filter=filterFieldWrDate;
        dataFilterWrDateV2.value1 = '2019-03-28';
        dataFilterWrDateV2.value2 = null;
        
        List<FE_DatatableController.DatatableFilterWrapper> appliedFilters = new List<FE_DatatableController.DatatableFilterWrapper>();
        appliedFilters.add(dataFilterWrStr);
        appliedFilters.add(dataFilterWrInt);
        appliedFilters.add(dataFilterWrIntV1);
        appliedFilters.add(dataFilterWrIntV2);
        appliedFilters.add(dataFilterWrDouble);
        appliedFilters.add(dataFilterWrDate);
        appliedFilters.add(dataFilterWrDateV1);
        appliedFilters.add(dataFilterWrDateV2);
          
        // When   
        Test.startTest();      	
        String result = FE_DatatableUtils.processAppliedFilters(appliedFilters);
        Test.stopTest();
        // Then
        System.assertNotEquals(result, null);
        
    }
    
 	@isTest
    static void TestmapDatatableActionsToWrappers(){ 
        
        //Given
        Datatable__c data = [Select id, ExternalId__c from Datatable__c where ExternalId__c like'TableTest%' Limit 1];
        RecordType recordT = [SELECT id FROM RecordType WHERE SobjectType = 'DatatableAction__c' AND DeveloperName = 'RowAction' LIMIT 1];
        List<DatatableAction__c> actionList = MockupFactory.createDatatableActions('testAction', 'testActionExternalId', 1, data.Id, recordT.Id);

        // When   
        Test.startTest();      	
        List<FE_DatatableController.DatatableActionWrapper> result = FE_DatatableUtils.mapDatatableActionsToWrappers(actionList);
        Test.stopTest();
        // Then
        System.assertNotEquals(result, null); 
    }

 	@isTest
    static void TestmapDatatableDataToWrappers(){ 
        
        //Given
		FE_DatatableController.DatatableElementWrapper dataW = new FE_DatatableController.DatatableElementWrapper();
        dataw.fieldName = 'Name';
        List<FE_DatatableController.DatatableElementWrapper> listDataw= new List<FE_DatatableController.DatatableElementWrapper>();
        listDataw.add(dataw);
        List<SObject> SOlist = new List<SObject>();
        
        // When   
        Test.startTest();
        List<Map<String,String>> result = FE_DatatableUtils.mapDatatableDataToWrappers(SOlist, listDataw);
        Test.stopTest();
        // Then
        System.assertNotEquals(result, null); 
    }    
    
}