src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>IsTemplate__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Identifies when a record represents a template</description>
        <label>Is Template</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>StructureComponent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Structure Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StructureNavigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Structure Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Contents (Structure Navigation)</relationshipLabel>
        <relationshipName>Contents1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContentCreateModalController.cls
public with sharing class ContentCreateModalController {

    @AuraEnabled(cacheable=false)
    public static String getRecordTypeName(String recordTypeId){
        if(String.isBlank(recordTypeId)){
            return null;
        }
        return Schema.SObjectType.Content__c.getRecordTypeInfosById().get(recordTypeId).getName();
    }

    @AuraEnabled(cacheable=false)
    public static String createNewContent(String recordTypeId, Boolean isTemplate, String componentId, String navigationUrl, String recordName, String clusterId, String templateId){
        try{
            String responseId;
            if(templateId == null){
                Content__c newContent = new Content__c(
                    Name = recordName.left(60),
                    RecordTypeId = recordTypeId,
                    IsTemplate__c = isTemplate,
                    StructureComponent__c = componentId,
                    StructureNavigation__c = getNavigationByUrl(navigationUrl),
                    Cluster__c = clusterId
                );
                insert newContent;
                responseId = newContent.Id;
            }else{
                responseId = ContentUtils.createFromTemplate(templateId, recordName, clusterId);
            }
            return responseId;
        }catch(DMLException e){
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getDMLMessage(0));
        }catch(Exception e){
            System.debug(e.getMessage());
            System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        } 
    }

    @AuraEnabled(cacheable=false)
    public static String getClusters(){
        // Prepare results
        List<LookupWrapper> results     = new List<LookupWrapper>();
        List<Cluster__c> clusters    = ClusterUtils.getClustersBelowList(getClusterUserId());
        String clusterIcon = 'custom:custom26';
        String sobjectName = GeneralUtils.prefix('[CMS]Cluster__c');

        for (Cluster__c cluster : clusters) {
            results.add(new LookupWrapper(cluster.Id, sobjectName, clusterIcon, cluster.Name, cluster.ExternalId__c + ' • '+ cluster.RecordType.Name));
        }

        return JSON.serialize(results);
    }

    public static Id getClusterUserId(){
        List<ClusterUser__c> clusterUser = [SELECT Id, Cluster__c FROM ClusterUser__c WHERE User__c =:UserInfo.getUserId() AND AccessLevel__c = 'Read/Write'];
        if(clusterUser.size() == 0)
         //   throw new AuraException('You have no cluster associated');
            throw new AuraHandledException('You have no cluster associated');
        return clusterUser.get(0).Cluster__c;
    }

    public static Id getNavigationByUrl(String url){
        List<Navigation__c> navs = [SELECT Id FROM Navigation__c WHERE URL__c = :url];
        if(!navs.isEmpty())
            return navs.get(0).Id;

        return null;
    }

}