src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Landscape</fullName>
                </value>
                <value>
                    <fullName>Portrait</fullName>
                </value>
                <value>
                    <fullName>Highlight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>AutomaticTransition__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determina si los contenidos transicionan o no de forma automática.</description>
        <inlineHelpText>Determina si los contenidos transicionan o no de forma automática.</inlineHelpText>
        <label>Automatic transition</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BannerFrameType__c</fullName>
        <defaultValue>&quot;Hero&quot;</defaultValue>
        <description>This field allows users to define the banner rather a small, medium or large on the page added</description>
        <inlineHelpText>Para presentación horizontal | Hero banner , 3 , 1 | Page banner , 6 , 1 | Tiny banner , 1 , 1 |||||| Para presentación vertical | Hero banner , 1 , 3 | Page banner , 1 , 6 | Tiny banner , 1 , 1</inlineHelpText>
        <label>Banner Frame Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>BannerFrameType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>BannerTransitionTime__c</fullName>
        <defaultValue>5000</defaultValue>
        <inlineHelpText>Time between content in milliseconds</inlineHelpText>
        <label>Banner transition time</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>BannerType__c</fullName>
        <description>Use this field to define the banner&apos;s behavior.</description>
        <label>Banner Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Carousel</fullName>
                </value>
                <value>
                    <fullName>Fade</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClusterExternalId__c</fullName>
        <formula>Cluster__r.ExternalId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All Articles</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
                <value>
                    <fullName>All Blocks</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DelayTime__c</fullName>
        <defaultValue>1000</defaultValue>
        <description>Time delay in milliseconds.</description>
        <inlineHelpText>Time delay in milliseconds.</inlineHelpText>
        <label>Delay Time</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Direction__c</fullName>
        <description>Use this field to set up on the component the direction that banner switch the content asociated</description>
        <label>Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Left</fullName>
                </value>
                <value>
                    <fullName>Right</fullName>
                    <default>true</default>
                    <label>Right</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventsType__c</fullName>
        <label>Events Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Landscape</fullName>
                </value>
                <value>
                    <fullName>Portrait</fullName>
                </value>
                <value>
                    <fullName>Highlight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExcludePastEvents__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude Past Events</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldsToSearch__c</fullName>
        <description>Content object fields to search for the inserted Global Search text</description>
        <inlineHelpText>Content object fields comma separated</inlineHelpText>
        <label>Fields To Search</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FirstCluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>First Cluster to make a cluster Tree in cluster selector component</description>
        <label>First Cluster to show</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 OR 2</booleanFilter>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterGroup</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components (First Cluster)</relationshipLabel>
        <relationshipName>Components1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HasDelay__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Delay</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HierarchicalOrderBy__c</fullName>
        <label>Cluster Hierarchy Order By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <label>Root to Leaf</label>
                </value>
                <value>
                    <fullName>DESC</fullName>
                    <label>Leaf to Root</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loop__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Determina el comportamiento del banner como un bucle.</description>
        <inlineHelpText>Determina el comportamiento del banner como un bucle.</inlineHelpText>
        <label>Loop</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <label>Order By</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Datasource__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CreatedDate ASC</fullName>
                    <default>true</default>
                    <label>Creation Date ASC</label>
                </value>
                <value>
                    <fullName>CreatedDate DESC</fullName>
                    <label>Creation Date DESC</label>
                </value>
                <value>
                    <fullName>Name ASC</fullName>
                </value>
                <value>
                    <fullName>Name DESC</fullName>
                </value>
                <value>
                    <fullName>Category__r.Name ASC</fullName>
                    <label>Category ASC</label>
                </value>
                <value>
                    <fullName>Category__r.Name DESC</fullName>
                    <label>Category DESC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c ASC</fullName>
                    <label>Publish Start Date ASC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c DESC</fullName>
                    <label>Publish Start Date DESC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c ASC</fullName>
                    <label>Event Start Date ASC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c DESC</fullName>
                    <label>Event Start Date DESC</label>
                </value>
                <value>
                    <fullName>Title__c ASC</fullName>
                    <label>Title ASC</label>
                </value>
                <value>
                    <fullName>Title__c DESC</fullName>
                    <label>Title DESC</label>
                </value>
                <value>
                    <fullName>Custom Sorting</fullName>
                </value>
                <value>
                    <fullName>Manual Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/globalValueSets/BannerFrameType.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Hero</fullName>
        <default>true</default>
        <label>Hero</label>
    </customValue>
    <customValue>
        <fullName>Page</fullName>
    </customValue>
    <customValue>
        <fullName>Square</fullName>
    </customValue>
    <customValue>
        <fullName>Custom</fullName>
    </customValue>
    <masterLabel>Banner Frame Type</masterLabel>
</GlobalValueSet>

src/classes/ObjectComponentWrapper.cls
public class ObjectComponentWrapper {
    
    public String Id;
    public String Name;
    public String RecordTypeId;
    public String RecordTypeName;
    public String RecordTypeDeveloperName;

    public String ArticleType;
    public Boolean AutomaticTransition;
    public String BannerFrameType;
    public Decimal BannerTransitionTime;
    public String BannerType;
    public String Cluster;
    public String ClusterExternalId;
    public String HierarchicalOrderBy;
    public String Datasource;
    public Decimal DelayTime;
    public String Direction;
    public String EventsType;
    public Boolean ExcludePastEvents;
    public String ExternalId;
    public String FieldsToSearch;
    public String FirstCluster;
    public Boolean HasDelay;
    public String LinkDetail;
    //Loop is a reserved word
    public Boolean LoopField;
    public String MatchCriteria;
    public String Mode;
    public String NavigationMode;
    public Boolean OnlyClusterLeaf;
    public String OrderBy;
    public String OrderByAdvance;
    public String Orientation;
    public Decimal PageSize;
    public String PagingType;
    public Boolean PredictiveSearchEnabled;
    public String SearchPlaceholder;
    public Boolean ShowBullets;
    public Boolean ShowDisplayMode;
    public Boolean ShowFilters;
    public Boolean ShowOrder;
    public Boolean ShowSearch;
    public String Status;
    public String StatusApprovalProcess;
    public String TagCriteria;

    public String LinkDetailURL;
    
    public ObjectComponentWrapper(Component__c component){
        try{this.Id = component.Id;}catch(Exception e){}
        try{this.Name = component.Name;}catch(Exception e){}
        try{this.RecordTypeId = component.RecordTypeId;}catch(Exception e){}
        try{this.RecordTypeName = component.RecordType.Name;}catch(Exception e){}
        try{this.RecordTypeDeveloperName = component.RecordType.DeveloperName;}catch(Exception e){}

        try{this.ArticleType = component.ArticleType__c;}catch(Exception e){}
        try{this.AutomaticTransition = component.AutomaticTransition__c;}catch(Exception e){}
        try{this.BannerFrameType = component.BannerFrameType__c;}catch(Exception e){}
        try{this.BannerTransitionTime = component.BannerTransitionTime__c;}catch(Exception e){}
        try{this.BannerType = component.BannerType__c;}catch(Exception e){}
        try{this.Cluster = component.Cluster__c;}catch(Exception e){}
        try{this.ClusterExternalId = component.ClusterExternalId__c;}catch(Exception e){}
        try{this.HierarchicalOrderBy = component.HierarchicalOrderBy__c;}catch(Exception e){}
        try{this.Datasource = component.Datasource__c;}catch(Exception e){}
        try{this.DelayTime = component.DelayTime__c;}catch(Exception e){}
        try{this.Direction = component.Direction__c;}catch(Exception e){}
        try{this.EventsType = component.EventsType__c;}catch(Exception e){}
        try{this.ExcludePastEvents = component.ExcludePastEvents__c;}catch(Exception e){}
        try{this.ExternalId = component.ExternalId__c;}catch(Exception e){}
        try{this.FieldsToSearch = component.FieldsToSearch__c;}catch(Exception e){}
        try{this.FirstCluster = component.FirstCluster__c;}catch(Exception e){}
        try{this.HasDelay = component.HasDelay__c;}catch(Exception e){}
        try{this.LinkDetail = component.LinkDetail__c;}catch(Exception e){}
        try{this.LoopField = component.Loop__c;}catch(Exception e){}
        try{this.MatchCriteria = component.MatchCriteria__c;}catch(Exception e){}
        try{this.Mode = component.Mode__c;}catch(Exception e){}
        try{this.NavigationMode = component.NavigationMode__c;}catch(Exception e){}
        try{this.OnlyClusterLeaf = component.OnlyClusterLeaf__c;}catch(Exception e){}
        try{this.OrderBy = component.OrderBy__c;}catch(Exception e){}
        try{this.OrderByAdvance = component.OrderByAdvance__c;}catch(Exception e){}
        try{this.Orientation = component.Orientation__c;}catch(Exception e){}
        try{this.PageSize = component.PageSize__c;}catch(Exception e){}
        try{this.PagingType = component.PagingType__c;}catch(Exception e){}
        try{this.PredictiveSearchEnabled = component.PredictiveSearchEnabled__c;}catch(Exception e){}
        try{this.SearchPlaceholder = component.SearchPlaceholder__c;}catch(Exception e){}
        try{this.ShowBullets = component.ShowBullets__c;}catch(Exception e){}
        try{this.ShowDisplayMode = component.ShowDisplayMode__c;}catch(Exception e){}
        try{this.ShowFilters = component.ShowFilters__c;}catch(Exception e){}
        try{this.ShowOrder = component.ShowOrder__c;}catch(Exception e){}
        try{this.ShowSearch = component.ShowSearch__c;}catch(Exception e){}
        try{this.Status = component.Status__c;}catch(Exception e){}
        try{this.StatusApprovalProcess = component.StatusApprovalProcess__c;}catch(Exception e){}
        try{this.TagCriteria = component.TagCriteria__c;}catch(Exception e){}
        try{this.RecordtypeDeveloperName = component.Recordtype.DeveloperName;}catch(Exception e){}

        try{this.LinkDetailURL = component.LinkDetail__r.URL__c;}catch(Exception e){}
    }

}