src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FormElement__c.object
<CustomObject>
    <description>Object that represents a field on a Community Form</description>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Form Element</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Element</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FormElementTriggersTest.cls
@isTest(seeAllData = false)
public class FormElementTriggersTest {
	
	@isTest 
	static void insertFormElementTest(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        Cluster__c cluster = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT')[0];
		//When
		Test.startTest();
		MockupFactory.createForm('testName', 'testName', 'testRetrieval', cluster.id);		
		Test.stopTest();
		//Then
		FormElement__c formElement = [SELECT id, ExternalId__c FROM FormElement__c LIMIT 1];
        System.assert(formElement.ExternalId__c != null);

	}

	@isTest
	static void updateFormElement(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        Cluster__c cluster = MockupFactory.createCluster('Argentina', null, 2, 'ClusterRoot', 'CRT')[0];
        MockupFactory.createForm('testName', 'testName', 'testRetrieval', cluster.id);
		//When
		Test.startTest();
		FormElement__c formElement = [SELECT id, name FROM FormElement__c LIMIT 1];
        formElement.name = 'updated';
        update formElement;
        Test.stopTest();
		//Then
		formElement = [SELECT id, ExternalId__c FROM FormElement__c LIMIT 1];
        System.assert(formElement.ExternalId__c != null);

	}
    
    @isTest
	static void incorrectObjectApiNameTest(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        Cluster__c cluster = MockupFactory.createCluster('Argentina', null, 2, 'ClusterRoot', 'CRT')[0];
        MockupFactory.createForm('testName', 'testName', 'testRetrieval', cluster.id);
		//When
		Test.startTest();
		FormElement__c formElement = [SELECT id, name FROM FormElement__c LIMIT 1];
        formElement.ObjectApiName__c = 'wrongApiName';
        try{
            update formElement;
        
        //Then
        }catch(DMLException e){
            system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
        Test.stopTest();

	}
    
    @isTest
	static void incorrectFieldApiNameTest(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        Cluster__c cluster = MockupFactory.createCluster('Argentina', null, 2, 'ClusterRoot', 'CRT')[0];
        MockupFactory.createForm('testName', 'testName', 'testRetrieval', cluster.id);
		//When
		Test.startTest();
		FormElement__c formElement = [SELECT id, name FROM FormElement__c LIMIT 1];
        formElement.ObjectApiName__c = '';
        try{
            update formElement;
        
        //Then
        }catch(DMLException e){
            system.assert(e.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
        Test.stopTest();

	}
}