src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <description>Object that represents a Form in a Community</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FormTriggersTest.cls
@isTest(seeAllData = false)
public class FormTriggersTest {
	
	@isTest 
	static void insertFormTest(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        Cluster__c cluster = MockupFactory.createCluster('Argentina', null, 1, 'ClusterRoot', 'CRT')[0];
		//When
		Test.startTest();
		MockupFactory.createForm('testName', 'testName', 'testRetrieval', cluster.id);		
		Test.stopTest();
		//Then
		Form__c form = [SELECT id, ExternalId__c FROM Form__c];
        System.assert(form.ExternalId__c != null);

	}

	@isTest
	static void updateForm(){
		//Given
		MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> clusterList = MockupFactory.createCluster('Argentina', null, 2, 'ClusterRoot', 'CRT');
        MockupFactory.createForm('testName', 'testName', 'testRetrieval', clusterList[0].id);
		//When
		Test.startTest();
		Form__c form = [SELECT id, name FROM form__c];
        form.name = 'updated';
        form.cluster__c = clusterList[1].id;
        update form;
        Test.stopTest();
		//Then
		form = [SELECT id, ExternalId__c FROM Form__c];
        System.assert(form.ExternalId__c != null);

	}
}