src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Form__c.object
<CustomObject>
    <description>Object that represents a Form in a Community</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Forms</relationshipLabel>
        <relationshipName>Forms</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RetrievalClass__c</fullName>
        <label>Retrieval Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SaveClass__c</fullName>
        <label>Save Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FormObjectsStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StyleClass__c</fullName>
        <label>Style Class</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Form</label>
    <nameField>
        <label>Form Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/FormElement__c.object
<CustomObject>
    <description>Object that represents a field on a Community Form</description>
    <fields>
        <fullName>ConfirmationError__c</fullName>
        <inlineHelpText>Complete with the error message when the confirmation is required and not ok</inlineHelpText>
        <label>Confirmation Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfirmationLabel__c</fullName>
        <inlineHelpText>Complete with the Field confirmation label when the field requires confirmation</inlineHelpText>
        <label>Confirmation Label</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfirmationPlaceholder__c</fullName>
        <label>Confirmation Placeholder</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ConfirmationRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if the field needs to be confirmed with a 2nd input (e.g. Email Confirmation)</inlineHelpText>
        <label>Confirmation Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DefaultValue__c</fullName>
        <label>Default Value</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldAPIName__c</fullName>
        <inlineHelpText>Complete with the field name defined in the Wrapper Class</inlineHelpText>
        <label>Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldLabel__c</fullName>
        <inlineHelpText>Complete with the label to display in the form</inlineHelpText>
        <label>Field Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FieldType__c</fullName>
        <label>Field Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>Numeric</fullName>
                </value>
                <value>
                    <fullName>Date</fullName>
                </value>
                <value>
                    <fullName>Picklist</fullName>
                </value>
                <value>
                    <fullName>Multi-Picklist</fullName>
                </value>
                <value>
                    <fullName>Radio Button</fullName>
                </value>
                <value>
                    <fullName>Multi-Checkbox</fullName>
                </value>
                <value>
                    <fullName>TextArea</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>FormSection__c</fullName>
        <label>Form Section</label>
        <referenceTo>FormSection__c</referenceTo>
        <relationshipLabel>Form Element</relationshipLabel>
        <relationshipName>FormFields</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>FormValidation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Form Validation</label>
        <referenceTo>FormValidation__c</referenceTo>
        <relationshipName>Form_Fields</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HelpText__c</fullName>
        <inlineHelpText>Complete with the information that will be displayed as help on the form field</inlineHelpText>
        <label>Help Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Select if the field is required</inlineHelpText>
        <label>Required</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaxLength__c</fullName>
        <label>Max Length</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <label>Object API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <inlineHelpText>Complete with the order of the field needs to be displayed in the form</inlineHelpText>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PicklistValues__c</fullName>
        <inlineHelpText>If type is Picklist, complete with the available values separated by comma</inlineHelpText>
        <label>Picklist Values</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PlaceHolder__c</fullName>
        <label>Place Holder</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ReadOnly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Read Only</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FormObjectsStatus</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>StyleClass__c</fullName>
        <inlineHelpText>Complete with the desired CSS class to be set</inlineHelpText>
        <label>Style Class</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TextAreaRows__c</fullName>
        <label>Text Area Rows</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Form Element</label>
    <nameField>
        <label>Form Field Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Element</pluralLabel>
    <recordTypes>
        <fullName>Field</fullName>
        <active>true</active>
        <label>Field</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FormSection__c.object
<CustomObject>
    <fields>
        <fullName>ColumnWidth__c</fullName>
        <label>Column Width</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Form__c</fullName>
        <label>Form</label>
        <referenceTo>Form__c</referenceTo>
        <relationshipLabel>Form Sections</relationshipLabel>
        <relationshipName>FormSections</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SectionTitle__c</fullName>
        <label>Section Title</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StyleClass__c</fullName>
        <label>Style Class</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Form Section</label>
    <nameField>
        <label>Form Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FormValidation__c.object
<CustomObject>
    <description>Object that represents a validation that is executed on a Community Form</description>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>Error Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalID__c</fullName>
        <externalId>true</externalId>
        <label>External ID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>RegularExpression__c</fullName>
        <inlineHelpText>Special text string for describing a search pattern</inlineHelpText>
        <label>Regular Expression</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>FormObjectsStatus</valueSetName>
        </valueSet>
    </fields>
    <label>Form Validation</label>
    <nameField>
        <label>Form Validation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Form Validations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/globalValueSets/FormObjectsStatus.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Active</fullName>
    </customValue>
    <customValue>
        <fullName>Inactive</fullName>
    </customValue>
    <description>Status Picklist Values for &quot;Form&quot; Objects</description>
    <masterLabel>Form Objects Status</masterLabel>
</GlobalValueSet>

src/classes/GeneralForm.cls
public without sharing class GeneralForm{
    public FormSettings formSettings;
    public Map<String, SObject> formData{get;set;}
    
    public GeneralForm(String formUniqueName, Set<Id> clusterIds){
        generateGeneralFormData(formUniqueName, clusterIds);
    }
    
    public GeneralForm(String formUniqueName, Set<Id> clusterIds, String recordId){
        generateGeneralFormData(formUniqueName, clusterIds);
        if(recordId != null && this.formSettings.retrievalClass != null){
            runMethod(this.formSettings.retrievalClass, this.formData, recordId);    
        }
    }
    
    public void generateGeneralFormData(String formUniqueName, Set<Id> clusterIds){
        if(clusterIds == null){
            clusterIds = new Set<Id>{null};
        }
        formData = new map<String, SObject>();
        List<FormSection__c> formSections = [SELECT  SectionTitle__c, StyleClass__c, Order__c, ColumnWidth__c,
                                                		Form__r.StyleClass__c, Form__r.ExternalID__c, Form__r.RetrievalClass__c, Form__r.SaveClass__c,
                                                		(SELECT FieldAPIName__c, FieldLabel__c, PlaceHolder__c, FieldType__c, HelpText__c, PicklistValues__c, IsRequired__c, ReadOnly__c, DefaultValue__c,
                                                         		StyleClass__c,ObjectAPIName__c , TextAreaRows__c,
                                                         		FormValidation__r.Status__c, FormValidation__r.ErrorMessage__c, FormValidation__r.RegularExpression__c,MaxLength__c,
		                                                    	ConfirmationRequired__c, ConfirmationLabel__c, ConfirmationError__c, ConfirmationPlaceholder__c 
           	                                          	   FROM FormFields__r 
                                                      	  WHERE Status__c = 'Active' 
                                                   	   ORDER BY Order__c ASC)
                                                  FROM FormSection__c 
                                                 WHERE Form__r.ExternalID__c =: formUniqueName AND Form__r.Status__c = 'Active' AND Form__r.Cluster__c IN :clusterIds ORDER BY Order__c ASC];
        

        System.debug('GeneralForm.generateGeneralFormData() method. formSections: ' + formSections);
        
        if(!formSections.isEmpty()){
            formSettings = new FormSettings(formSections.get(0).Form__r.ExternalID__c, formSections.get(0).Form__r.StyleClass__c,
                                            formSections.get(0).Form__r.RetrievalClass__c, formSections.get(0).Form__r.SaveClass__c
                                           );
            Map<String,Schema.SObjectType> globalDescribe = Schema.getGlobalDescribe();

            for(FormSection__c formSection : formSections){
                Section currentSection = new Section(formSection);
                formSettings.sections.add(currentSection);
                for(FormElement__c formField : formSection.FormFields__r){
                    Boolean isCalculatedOrFormula = getIsCalculatedOrFormulaField(globalDescribe, formField.ObjectAPIName__c, formField.FieldAPIName__c);
                    String fieldValue = formField.DefaultValue__c != null ? formField.DefaultValue__c : null;
                    currentSection.fields.add(new Element(formField));
                    if(!formData.containsKey(formField.ObjectAPIName__c)){
                    	SObject obj = globalDescribe.get(formField.ObjectAPIName__c).newSobject();
                        formData.put(formField.ObjectAPIName__c, obj);
                    }
                    if(!isCalculatedOrFormula){
                        formData.get(formField.ObjectAPIName__c).put(formField.FieldAPIName__c, fieldValue);
                    }else{
                        formData.put(formField.ObjectAPIName__c, addNonEditableField(JSON.serialize(formData.get(formField.ObjectAPIName__c)), formField.FieldAPIName__c, fieldValue,formField.FieldType__c, formField.ObjectAPIName__c));
                    }
                }
            }
        }else{
            throw new FormConstructionException('No Form was found with name: ' + formUniqueName);
        }
    }
    
    private static void runMethod(String className, Map<String, SObject> formData, String recordId){
        Type t  = Type.forName(className);
        if(t != null){
            FormRetrievalInterface formRetrieval = (FormRetrievalInterface)t.newInstance();
            formData = formRetrieval.execute(formData, recordId);
        }
    }
    
    public static FormResponseWrapper saveForm(String formSettingsString, Map<String, SObject> formData){
        FormSettings formSettings = (FormSettings)JSON.deserialize(formSettingsString, FormSettings.class);
        if(!Test.isRunningTest()){
            Type t  = Type.forName(formSettings.saveClass);
            if(t != null){
                FormSaveInterface formSave = (FormSaveInterface)t.newInstance();
                return formSave.execute(formData);
            }
        }
        return null;
    }
    /*
		As a work around to add non editable fields to the form data, we serialize the object, add the field, then deserialize it.
	*/
    private sObject addNonEditableField(String serializedObject, String fieldApiName, String fieldValue, String fieldType, String objectType){
        serializedObject = serializedObject.substring(0, serializedObject.lastIndexOf('}'));
        if(fieldValue != null)
			serializedObject = serializedObject + ',"' + fieldApiName + '":"' + fieldValue + '"}';
        else{
             	serializedObject = serializedObject + ',"' + fieldApiName + '":null}';
            
        }
        system.debug('serializedobj' + serializedObject);
        return (SObject)JSON.deserialize(serializedObject, Type.forName(objectType));
        
    }
    
    private Boolean getIsCalculatedOrFormulaField(Map<String,Schema.SObjectType> globalDescribe, String objName, String fieldName){
        return fieldName == 'createdDate' ||
            fieldName == 'lastModifiedDate' || 
            globalDescribe.get(objName).getDescribe().fields.getMap().get(fieldName).getDescribe().isCalculated() || 
            globalDescribe.get(objName).getDescribe().fields.getMap().get(fieldName).getDescribe().isAutonumber();
    }
    
    class FormConstructionException extends Exception{}
    
    @TestVisible
    class FormSettings{
        public String saveClass;
        public String retrievalClass;
        public String styleClass;
        public String uniqueFormName;
        public List<Section> sections;
        
        public FormSettings(String uniqueFormName, String styleClass, String retrievalClass, String saveClass){
            this.styleClass = styleClass;
            this.uniqueFormName = uniqueFormName;
            this.sections = new List<Section>();
            this.retrievalClass = retrievalClass;
            this.saveClass = saveClass;
        }
    }
    class Section{
        public String SectionTitle;
        public String styleClass;
        public Integer order;
        public List<Element> fields;
        public String sectionWidth;
        
        public Section(FormSection__c formSection){
            this.sectionTitle = formSection.SectionTitle__c;
            this.styleClass = formSection.StyleClass__c;
            this.order = (Integer)formSection.Order__c;
            this.fields = new List<Element>();
            this.sectionWidth = formSection.ColumnWidth__c;
            if(formSection.FormFields__r.isEmpty()){
                throw new FormConstructionException('A section does not have any field');
            }
        }
    }
    class Element{
        public String objApiName;
        public String apiName;
        public String displayType;
        public String label;
        public String placeHolder;
        public String helpText;
        public Boolean isRequired;
        public Boolean readOnly;
        public String defaultValue;
        public String styleClass;
        public List<String> picklistValues;
        public Boolean hasValidation;
        public String validationErrorMessage;
        public String validationRegExp;
        public String fieldMask;
        public Integer maxLength;
        public Boolean hasConfirmation;
        public String confirmationLabel;
        public String confirmationPlaceholder;
        public String confirmationErrMessage;
        public Integer textAreaRows;
        
        public Element(FormElement__c field){
            this.objApiName = field.ObjectAPIName__c;
            this.apiName = field.FieldAPIName__c;
            this.displayType = field.FieldType__c;
            this.textAreaRows = Integer.valueOf(field.TextAreaRows__c);
            this.label = field.FieldLabel__c;
            this.placeHolder = field.PlaceHolder__c;
            this.helpText = field.HelpText__c;
            this.isRequired = field.IsRequired__c;
            this.readOnly = field.ReadOnly__c;
            this.defaultValue = field.defaultValue__c;
            this.styleClass = field.StyleClass__c;
            this.picklistValues = field.PicklistValues__c != null ? field.PicklistValues__c.split(';') : null;
            if(field.FormValidation__r != null){
                this.hasValidation = field.FormValidation__r.Status__c == 'Active' ? field.FormValidation__r != NULL : false;
                this.validationErrorMessage = field.FormValidation__r.Status__c == 'Active' ? field.FormValidation__r.ErrorMessage__c : null;
                this.validationRegExp = field.FormValidation__r.Status__c == 'Active' ? field.FormValidation__r.RegularExpression__c : null;
            }
            this.maxLength = (Integer)field.MaxLength__c;
            this.hasConfirmation = field.ConfirmationRequired__c;
            this.confirmationLabel = field.ConfirmationLabel__c;
            this.confirmationPlaceholder = field.ConfirmationPlaceholder__c;
            this.confirmationErrMessage = field.ConfirmationError__c;            
            
        }
    }
}