src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ClusterRootExternalId__c</fullName>
        <formula>if(RecordType.DeveloperName = &apos;ClusterRoot&apos;, ExternalId__c, &apos;&apos;) 
+
if(ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, ParentCluster__r.ExternalId__c, &apos;&apos;) 
+ 
if(ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;) 
+ 
if(ParentCluster__r.ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, ParentCluster__r.ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster Root External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Represents menu options than can be related to other menu options.</description>
    <fields>
        <fullName>Behaviour__c</fullName>
        <label>Behaviour</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Tab</fullName>
                </value>
                <value>
                    <fullName>Same Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClusterRootExternalId__c</fullName>
        <formula>if(Cluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ExternalId__c, &apos;&apos;)
+
if(Cluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)
+
if(Cluster__r.ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)
+
if(Cluster__r.ParentCluster__r.ParentCluster__r.ParentCluster__r.RecordType.DeveloperName = &apos;ClusterRoot&apos;, Cluster__r.ParentCluster__r.ParentCluster__r.ParentCluster__r.ExternalId__c, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster Root External Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ComponentName__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MenuIcon__c</fullName>
        <label>Menu Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MenuLabel__c</fullName>
        <label>Menu Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentMenu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>ParentMenus</relationshipLabel>
        <relationshipName>SubMenus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URLParameters__c</fullName>
        <label>URL Parameters</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <description>Represents the highest level of a Menu tree. It can be asociated to a component. (Ex. File)</description>
        <label>Menu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Behaviour__c</fullName>
        <label>Behaviour</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Tab</fullName>
                </value>
                <value>
                    <fullName>Same Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Status</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <recordTypes>
        <fullName>Navigation</fullName>
        <active>true</active>
        <description>Internal or external navigation points. They are mostly references to community pages.</description>
        <label>Navigation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ObjectMenuWrapper.cls
public class ObjectMenuWrapper {
    
    public String Id;
    public String Name;
    public String RecordTypeId;
    public String RecordTypeName;
    public String RecordTypeDeveloperName;

    public String Behaviour;
    public String Cluster;
    public String ClusterRootExternalId;
    public String ComponentName;
    public String ExternalId;
    public String MenuIcon;
    public String MenuLabel;
    public String Navigation;
    public String ParentMenu;
    public String Status;
    public String URLParameters;
    
    public String NavigationURL;
    
    public ObjectMenuWrapper(Menu__c menu){
        try{this.Id = menu.Id;}catch(Exception e){}
        try{this.Name = menu.Name;}catch(Exception e){}
        try{this.RecordTypeId = menu.RecordTypeId;}catch(Exception e){}
        try{this.RecordTypeName = menu.RecordType.Name;}catch(Exception e){}
        try{this.RecordTypeDeveloperName = menu.RecordType.DeveloperName;}catch(Exception e){}
        
        try{this.Behaviour = menu.Behaviour__c;}catch(Exception e){}
        try{this.Cluster = menu.Cluster__c;}catch(Exception e){}
        try{this.ClusterRootExternalId = menu.ClusterRootExternalId__c;}catch(Exception e){}
        try{this.ComponentName = menu.ComponentName__c;}catch(Exception e){}
        try{this.ExternalId = menu.ExternalId__c;}catch(Exception e){}
        try{this.MenuIcon  = menu.MenuIcon__c;}catch(Exception e){}
        try{this.MenuLabel = menu.MenuLabel__c;}catch(Exception e){}
        try{this.Navigation = menu.Navigation__c;}catch(Exception e){}
        try{this.ParentMenu = menu.ParentMenu__c;}catch(Exception e){}
        try{this.Status = menu.Status__c;}catch(Exception e){}
        try{this.URLParameters = menu.URLParameters__c;}catch(Exception e){}
        try{this.NavigationURL = menu.Navigation__r.URL__c;}catch(Exception e){}
    }

}