src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterLeaf</fullName>
        <active>true</active>
        <description>Represents the lowest level of the clustering tree. Community users will be related to this cluster level. (Ex.: Argentina Consumers)</description>
        <label>Cluster Leaf</label>
    </recordTypes>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Datatables</relationshipLabel>
        <relationshipName>ListViews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ObjectApiName__c</fullName>
        <label>Object Api Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/DatatableTriggersTest.cls
@isTest
private class DatatableTriggersTest {
    
    @testSetup
    static void generateCustomSettings(){
        MockupFactory.generateAcceleratorSetting();
    }
    
    @isTest
    static void createValidDatatable() {
        
        Test.startTest();
        List<Cluster__c> clusters = MockUpFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot', 'CRT');
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 2, clusters.get(0).Id);
        
        System.assert(datatables.size() > 0);
        
        Test.stopTest();
    }
    
    @isTest
    static void updateValidDatatable() {
        
        Test.startTest();
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        List<Cluster__c> clustersLeaf = MockUpFactory.createCluster('DummyLeafCluster', clustersRoot[0].Id, 1, 'ClusterLeaf', 'CLT');
        
        Cluster__c leaf = clustersLeaf[0];
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 2, leaf.Id);
        
        System.assert(datatables.size() > 0);
        
        Datatable__c a = datatables.get(0);
        a.Name = 'DummyDatatable2';
        a.Cluster__c = clustersRoot[0].Id;
        
        update a;
        
       /* a = datatables.get(0);
        a.Name = 'DummyDatatable2';
        a.Cluster__c = null;
        
        update a;*/
        
        Test.stopTest();
    }
    
    @isTest
    static void updateObjectOfValidDatatable() {
        
        Test.startTest();
        List<Cluster__c> clustersRoot = MockUpFactory.createCluster('DummyRootCluster', null, 1, 'ClusterRoot', 'CRT');
        List<Cluster__c> clustersLeaf = MockUpFactory.createCluster('DummyLeafCluster', clustersRoot[0].Id, 1, 'ClusterLeaf', 'CLT');
        
        Cluster__c leaf = clustersLeaf[0];
        
        List<Datatable__c> datatables = MockupFactory.createDatatables('DummyDatatable', 'DummyDatatable', 'Account', 2, leaf.Id);
        
        System.assert(datatables.size() > 0);
        
        Datatable__c a = datatables.get(0);
        a.Name = 'DummyDatatable2';
        a.ObjectApiName__c = 'Case';
        a.Cluster__c = clustersRoot[0].Id;
        
        update a;
        
       /* a = datatables.get(0);
        a.Name = 'DummyDatatable2';
        a.Cluster__c = null;
        
        update a;*/
        
        Test.stopTest();
    }
    
    @isTest
    static void createInvalidDatatableWithExternalId() {
        
        Test.startTest();
        List<Cluster__c> clusters = MockUpFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot', 'CRT');
        List<Datatable__c> datatables = new List<Datatable__c>();
        
        String name = 'DummyDatatable';
        
        Datatable__c datatable = new Datatable__c();
        datatable.Name = name;
        datatable.Cluster__c = clusters.get(0).Id;
        datatable.ExternalId__c = name;
        datatable.ObjectApiName__c = 'DummyObject';
        
        datatables.add(datatable);
        
        List<Database.SaveResult> results = Database.insert(datatables, false);
        
        Test.stopTest();
    }
    
    @isTest
    static void createInvalidDatatableWithoutExternalId() {
        
        Test.startTest();
        List<Cluster__c> clusters = MockUpFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot', 'CRT');
        List<Datatable__c> datatables = new List<Datatable__c>();
        
        String name = 'DummyDatatable';
        
        Datatable__c datatable = new Datatable__c();
        datatable.Name = name;
        datatable.Cluster__c = clusters.get(0).Id;
        datatable.ExternalId__c = null;
        datatable.ObjectApiName__c = 'DummyObject';
        
        datatables.add(datatable);
        
        List<Database.SaveResult> results = Database.insert(datatables, false);
        
        Test.stopTest();
    }

    //CMS-315 Apex Sharing on Datatable
    @isTest
    static void updateDatatableSharing(){
        // Given
        List<Cluster__c> clusterRootList = MockupFactory.createCluster('ClusterRootTest', null, 1, 'ClusterRoot', 'DRC');
        List<Datatable__c> datatableList = MockupFactory.createDatatables('Table Test', 'TableTest', GeneralUtils.prefix('[CMS]Component__c'), 1, clusterRootList[0].Id);
        List<DatatableElement__c> dataElementList = MockupFactory.createDatatableElements('Name', 'DataElementExternalId', 2, datatableList[0].Id);
        datatableList[0].Cluster__c = clusterRootList[0].Id;
        
        // When
        Test.startTest();
        update datatableList[0];
        Test.stopTest();

        // Then
        List<Datatable__Share> shareList = [SELECT Id, ParentId FROM Datatable__Share WHERE ParentId = :datatableList[0].Id AND RowCause =: GeneralUtils.prefix('[CMS]Clustering__c')];
        System.assertEquals(3, shareList.size());
    }
}