src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ArticleType__c</fullName>
        <label>Article Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Landscape</fullName>
                </value>
                <value>
                    <fullName>Portrait</fullName>
                </value>
                <value>
                    <fullName>Highlight</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All Articles</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
                <value>
                    <fullName>All Blocks</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>HierarchicalOrderBy__c</fullName>
        <label>Cluster Hierarchy Order By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <label>Root to Leaf</label>
                </value>
                <value>
                    <fullName>DESC</fullName>
                    <label>Leaf to Root</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PageSize__c</fullName>
        <label>Page Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LinkDetail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Link Detail</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Contents</relationshipLabel>
        <relationshipName>Contents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/ContentAssignment__c.object
<CustomObject>
    <description>Manages the direct assignment of Content to Components</description>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Content Assignment</relationshipLabel>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <referenceTo>Content__c</referenceTo>
        <relationshipName>ComponentContentAssignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content Assignment</label>
    <nameField>
        <displayFormat>CA-{000000}</displayFormat>
        <label>Content Assignment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <recordTypes>
        <fullName>Navigation</fullName>
        <active>true</active>
        <description>Internal or external navigation points. They are mostly references to community pages.</description>
        <label>Navigation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_BaseComponentControllerTest.cls
@isTest(seeAllData = false)
public with sharing class CG_BaseComponentControllerTest {
    @testSetup
    static void setup(){
        // Given in all cases
        MockupFactory.generateAcceleratorSetting();
        MockupFactory.createCluster('global', null, 1, 'ClusterRoot', 'CRT');
    }
    @isTest 
    static void CASE_1(){
        /*  Comment: dado un String correspondiente al ExternalId__c de un Component__c se retorna un Wrapper 
            con el Component correspondiente, es un related new con datasourse 'Parent Component Behaviour' y un pagesize */
    
        //Given
        //Navigation Record
        Navigation__c nav = new Navigation__c(Name = 'Nav', URL__c = 'https:google.com');
        //Component Article Record
        String recordTypeId = [SELECt id, name, SobjectType FROM RecordType WHERE SobjectType = 'Component__c' AND Name = 'Article' LIMIT 1].id;
        Component__c componentArticle = new Component__c (Name='Article', ExternalId__c='Article', RecordTypeId = recordTypeId, Datasource__c = 'ManualAssignment',HierarchicalOrderBy__c = 'ASC', LinkDetail__c = nav.id);
        insert componentArticle;
        //Content Article Record
        String RTArticleId = [SELECt id, name, SobjectType FROM RecordType WHERE SobjectType = 'Content__c' AND Name = 'Article'].id;
        Content__c contentArticle = new Content__c(Name = 'Article1', RecordTypeId = RTArticleId);
        insert contentArticle;
        //Component Related Article Record
        recordTypeId = [SELECt id, name, SobjectType FROM RecordType WHERE SobjectType = 'Component__c' AND Name = 'Related Article' LIMIT 1].id;
        Component__c componentRN = new Component__c (Name='RN', ExternalId__c='RN', RecordTypeId = recordTypeId, Datasource__c = 'ParentComponentBehaviour', ArticleType__c = 'Landscape', PageSize__c = 1,HierarchicalOrderBy__c = 'ASC', LinkDetail__c = nav.id);
        insert componentRN;
        //When
        test.startTest();
        CG_BaseComponentController.ComponentWrapper cw = CG_BaseComponentController.getComponentWrapper(componentRN.ExternalId__c, 'RelatedArticle', componentArticle.Id, contentArticle.Id, null, 'DESKTOP');
        test.stopTest();
        //Then
        system.assertNotEquals(null, cw);
        system.assertEquals(componentRN.id, cw.component.id);
    }   
    @isTest 
    static void CASE_2(){
        /*  Comment: dado un String correspondiente al ExternalId__c de un Component__c se retorna un Wrapper 
            con el Component correspondiente, es un Banner con datasourse 'Manual Assigment'  */
    
        //Given
        String clusterId = [SELECT id FROM Cluster__c LIMIT 1].Id;
        //Component Banner Record
        String recordTypeId = [SELECt id, name, SobjectType FROM RecordType WHERE SobjectType = 'Component__c' AND Name = 'Banner' LIMIT 1].id;
        Component__c componentBanner = new Component__c (Name='Article', ExternalId__c='Article', RecordTypeId = recordTypeId, Datasource__c = 'ManualAssignment',HierarchicalOrderBy__c = 'ASC');
        insert componentBanner;
        //Content Banner Record
        String RTBannerId = [SELECt id, name, SobjectType FROM RecordType WHERE SobjectType = 'Content__c' AND Name = 'Banner'].id;
        Content__c contentBanner = new Content__c(Name = 'Article1', RecordTypeId = RTBannerId);
        insert contentBanner;
        // Component Content Junction Record
        ContentAssignment__c ca = new ContentAssignment__c(Component__c=componentBanner.id, Content__c=contentBanner.id);
        insert ca;
        //When
        test.startTest();
        CG_BaseComponentController.ComponentWrapper cw = CG_BaseComponentController.getComponentWrapper(componentBanner.ExternalId__c, 'Banner', null, null, null, 'DESKTOP');
        test.stopTest();
        //Then
        system.assertNotEquals(null, cw);
        system.assertEquals(componentBanner.id, cw.component.id);
    }
    @isTest 
    static void CASE_3(){
        /*  Comment: Prueba del paginado */
    
        //Given
        Cluster__c cluster = [SELECT id FROM Cluster__c LIMIT 1];
        List<String> listContentId = new List<String>();
        for(Content__c con : MockupFactory.createContent('Article', cluster, 3)){
            listContentId.add(con.Id);
        }
        //When
        test.startTest();
        List<CG_BaseComponentController.ContentWrapper> listContentWrapper = CG_BaseComponentController.getPage(listContentId, 'Article', '1', '1', 'ExternalId__c', 'DESKTOP');
        test.stopTest();
        //Then
        system.assertNotEquals(null, listContentWrapper);
    }
}