src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>5</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Components</relationshipLabel>
        <relationshipName>Components</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <description>Configure a new Menu component that has associated Menu records. They can be ordered manually.</description>
        <label>Menu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Menu__c.object
<CustomObject>
    <description>Represents menu options than can be related to other menu options.</description>
    <fields>
        <fullName>Behaviour__c</fullName>
        <label>Behaviour</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Tab</fullName>
                </value>
                <value>
                    <fullName>Same Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Menus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ComponentName__c</fullName>
        <label>Component Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>MenuIcon__c</fullName>
        <label>Menu Icon</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MenuLabel__c</fullName>
        <label>Menu Label</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Menus</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentMenu__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Menu</label>
        <referenceTo>Menu__c</referenceTo>
        <relationshipLabel>ParentMenus</relationshipLabel>
        <relationshipName>SubMenus</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>URLParameters__c</fullName>
        <label>URL Parameters</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Menu</label>
    <nameField>
        <label>Menu Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Menus</pluralLabel>
    <recordTypes>
        <fullName>Menu</fullName>
        <active>true</active>
        <description>Represents the highest level of a Menu tree. It can be asociated to a component. (Ex. File)</description>
        <label>Menu</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Behaviour__c</fullName>
        <label>Behaviour</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Tab</fullName>
                </value>
                <value>
                    <fullName>Same Tab</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>ClusterRoot</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Navigations</relationshipLabel>
        <relationshipName>Navigations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URLMask__c</fullName>
        <label>URL Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SidebarMenuController.cls
public class SidebarMenuController extends ComponentManager{
    
	//WRAPPERS
    public class SidebarComponentWrapper extends ComponentManager.DataWrapper{
		@auraEnabled public List<NavWrapper> navWrapper;
        @AuraEnabled public String device;
        

		public SidebarComponentWrapper (String componentExternalId, String clusterId, String device){
			this.navWrapper = new List<NavWrapper>();
            this.device = device;
		}
	}

	public class NavWrapper {
        @auraEnabled public ObjectMenuWrapper menu {get;set;}
        @auraEnabled public String behaviour {get;set;}
        @auraEnabled public String iconName {get;set;}

        public NavWrapper(Menu__c menu) {
            this.menu = new ObjectMenuWrapper(menu);
            this.menu.MenuDynamicLabel = GeneralUtils.replaceDynamicFields(this.menu.MenuDynamicLabel, 'User', UserInfo.getUserId(), false);
            this.behaviour = menu.Navigation__r.Behaviour__c == 'New Tab' ? '_blank' : '_self';
            this.iconName = menu.MenuIcon__c;
    	}
	}
    
    @AuraEnabled
    public static ComponentWrapper getComponentWrapper(String componentExternalId, String clusterId, String device){
        SidebarMenuController ctrl = new SidebarMenuController();
        ctrl.customPermissionView = 'Menu View Frame';
        ctrl.customPermissionEdit = 'Menu Edit Frame';
        ctrl.componentFieldSet = new set<String>{
            'Id'};
        ctrl.componentExternalId = componentExternalId;
        ctrl.clusterId = clusterId;
        ctrl.device = device;

        return ctrl.getCW();
    }
    

	
	private static SidebarComponentWrapper getNavWrapper(String componentExternalId, String clusterId, String device) {
  		if(clusterId == null || clusterId.trim() == ''){
			clusterId = ClusterUtils.getClusterIdFromMappingObject(UserInfo.getUserId(), Network.getNetworkId());
		}
		//Armado del Component Wrapper
		SidebarComponentWrapper scw = new SidebarComponentWrapper(componentExternalId, clusterId, device);
		scw.navWrapper = getWrapperFromComponent(componentExternalId, clusterId, device);
		return scw;
	}

	
	private static List<NavWrapper> getWrapperFromComponent(String componentExternalId, String clusterId, String device){
		// Busqueda de Menus con Assignments al Component
		List<MenuAssignment__c> menuAssignments = [SELECT Id, Component__c, Component__r.Cluster__c, Menu__c, Menu__r.Cluster__c 
		FROM MenuAssignment__c WHERE Component__r.ExternalId__c =: componentExternalId ORDER BY Order__c ASC];
        List<String> menuIds = new List<String>();
		Set<String> parentClusterIds = ClusterUtils.getClustersParents(clusterId);
		for(MenuAssignment__c ma : menuAssignments){
			if(parentClusterIds.contains(ma.Menu__r.Cluster__c)){
				menuIds.add(ma.Menu__c);
			}
		}
		List<NavWrapper> menuWrappers = new List<NavWrapper>();
		List<Menu__c> menuList = getMenuList(menuIds, device);
		for(Menu__c menu : menuList){
            NavWrapper newWrapper = new NavWrapper(menu);
   			menuWrappers.add(newWrapper);      
		}
		return menuWrappers;
	}


	// Traemos todos los SubMenus relacionados a los Menus del Component	
	private static List<Menu__c> getMenuList(List<String> menuIds, String device){
        String displayOn;
        if(device.equals('DESKTOP')){
            displayOn = 'Desktop';
        }else{
            displayOn = 'Mobile';
        }
		return [SELECT Id, MenuLabel__c, MenuDynamicLabel__c, Cluster__c, Navigation__r.URL__c, MenuIcon__c, ComponentName__c, URLParameters__c, Navigation__r.Behaviour__c, Navigation__r.UrlMask__c, StyleClass__c FROM Menu__c 
                WHERE ParentMenu__c =: menuIds AND (DisplayOn__c = :displayOn OR DisplayOn__c = 'Both') 
    			];
	}
    
    
    public override DataWrapper getData() {
    	SidebarComponentWrapper scw = getNavWrapper(componentExternalId, clusterId, device);
        return scw;
    }

}