src/objects/Cluster__c.object
<CustomObject>
    <description>Allows organizations to group content based on any criteria (geographical regions, countries, persona types) and apply governance through the hierarchy (ex. define a global banner for all countries using the same community).</description>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <recordTypes>
        <fullName>ClusterRoot</fullName>
        <active>true</active>
        <description>Represents the highest level of the clustering tree or the only cluster applicable for a community. (Ex. Global)</description>
        <label>Cluster Root</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Datatable__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Datatables</relationshipLabel>
        <relationshipName>ListViews</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Datatable</label>
    <nameField>
        <label>Datatable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Datatables</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FE_DynamicPicklistDatatableTest.cls
@isTest
public class FE_DynamicPicklistDatatableTest {
    
    @testSetup
    public static void testSetup() {
        MockupFactory.generateAcceleratorSetting();
        List<Cluster__c> clusters = MockupFactory.createCluster('DummyCluster', null, 1, 'ClusterRoot', 'DummyCluster');
        
        List<Datatable__c>  datatables = MockupFactory.createDatatables('DatatableDummy', 'DatatableDummy', 'Case', 1, clusters.get(0).Id);		            
    }
    
    @isTest
    public static void getDefaultValueTest01() {
        Test.startTest();
        FE_DynamicPicklistDatatable dp = new FE_DynamicPicklistDatatable();
        
        System.debug(dp.getDefaultValue());
        
        Test.stopTest();
    }
    
    @isTest
    public static void getValuesTest01() {
        Test.startTest();
        FE_DynamicPicklistDatatable dp = new FE_DynamicPicklistDatatable();
        
        System.debug(dp.getValues());
        
        Test.stopTest();
    }
}