src/objects/CMSContentSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to be configured by the CMS implementator for object Content.</description>
    <fields>
        <fullName>ContentLandingColumnFields__c</fullName>
        <label>Content Landing Column Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentLandingRecordTypes__c</fullName>
        <label>Content Landing RecordTypes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContentTemplateRecordTypes__c</fullName>
        <label>Content Template RecordTypes</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>CMS Content Settings</label>
</CustomObject>

src/objects/CMSMediaElementSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to be configured by the CMS implementator for object Media Element.</description>
    <fields>
        <fullName>EnableMediaElementAutomaticResize__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If true, the user will have the option to resize a desktop image for tablet and/or mobile.</description>
        <inlineHelpText>If true, the user will have the option to resize a desktop image for tablet and/or mobile.</inlineHelpText>
        <label>Enable Media Element Automatic Resize</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MaxSizeDesktop__c</fullName>
        <defaultValue>1280</defaultValue>
        <description>Defines the maximum size (logical resolution) that an image can have for desktop when uploading a media element.</description>
        <inlineHelpText>Defines the maximum size (logical resolution) that an image can have for desktop when uploading a media element.</inlineHelpText>
        <label>Max. Size Desktop</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaxSizeMobile__c</fullName>
        <defaultValue>480</defaultValue>
        <label>Max. Size Mobile</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MaxSizeTablet__c</fullName>
        <defaultValue>768</defaultValue>
        <description>Defines the maximum size (logical resolution) that an image can have for tablet when uploading a media element.</description>
        <inlineHelpText>Defines the maximum size (logical resolution) that an image can have for tablet when uploading a media element.</inlineHelpText>
        <label>Max. Size Tablet</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>CMS Media Element Settings</label>
</CustomObject>

src/objects/CMSSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to be configured by the CMS implementator.</description>
    <fields>
        <fullName>SalesforceDomain__c</fullName>
        <label>Salesforce Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClusterFieldForPublicGroups__c</fullName>
        <defaultValue>&quot;[CMS]ExternalId__c&quot;</defaultValue>
        <description>When a cluster is created, a public group is created. This field determines which cluster field will be used as the name of the public group that is created for the cluster.</description>
        <inlineHelpText>When a cluster is created, a public group is created. This field determines which cluster field will be used as the name of the public group that is created for the cluster.</inlineHelpText>
        <label>Cluster Field for Public Groups</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CMS Settings</label>
</CustomObject>

src/classes/CustomSettingWrapper.cls
public class CustomSettingWrapper {
    
    @AuraEnabled public String ClusterFieldForPublicGroups;
    @AuraEnabled public String SalesforceDomain;
    @AuraEnabled public String ContentLandingColumnFields;
    @AuraEnabled public String ContentLandingRecordTypes;
    @AuraEnabled public String ContentTemplateRecordTypes;
    @AuraEnabled public Decimal MaxSizeDesktop;
    @AuraEnabled public Decimal MaxSizeMobile;
    @AuraEnabled public Decimal MaxSizeTablet;
    @AuraEnabled public Boolean EnableMediaElementAutomaticResize;
    
    public CustomSettingWrapper(CMSSettings__c cmsSetting, CMSContentSettings__c contentSetting, CMSMediaElementSettings__c meSetting){
        this.ClusterFieldForPublicGroups = cmsSetting.ClusterFieldForPublicGroups__c;
        this.SalesforceDomain = cmsSetting.SalesforceDomain__c;
        this.ContentLandingColumnFields = contentSetting.ContentLandingColumnFields__c;
        this.ContentLandingRecordTypes = contentSetting.ContentLandingRecordTypes__c;
        this.ContentTemplateRecordTypes = contentSetting.ContentTemplateRecordTypes__c;
        this.MaxSizeDesktop = meSetting.MaxSizeDesktop__c;
        this.MaxSizeMobile = meSetting.MaxSizeMobile__c;
        this.MaxSizeTablet = meSetting.MaxSizeTablet__c;
        this.EnableMediaElementAutomaticResize = meSetting.EnableMediaElementAutomaticResize__c;
    }

}