src/objects/CMSContentSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to be configured by the CMS implementator for object Content.</description>
    <label>CMS Content Settings</label>
</CustomObject>

src/objects/CMSMediaElementSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to be configured by the CMS implementator for object Media Element.</description>
    <label>CMS Media Element Settings</label>
</CustomObject>

src/objects/CMSSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Settings to be configured by the CMS implementator.</description>
    <label>CMS Settings</label>
</CustomObject>

src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>Datasource__c</fullName>
        <label>Datasource</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ManualAssignment</fullName>
                    <label>Manual Assignment</label>
                </value>
                <value>
                    <fullName>Tags</fullName>
                </value>
                <value>
                    <fullName>Categories</fullName>
                </value>
                <value>
                    <fullName>TagsCategories</fullName>
                    <label>Tags + Categories</label>
                </value>
                <value>
                    <fullName>ParentComponentBehaviour</fullName>
                    <label>Parent Component Behaviour</label>
                </value>
                <value>
                    <fullName>ParentContentTags</fullName>
                    <label>Parent Content Tags</label>
                </value>
                <value>
                    <fullName>ParentContentCategories</fullName>
                    <label>Parent Content Categories</label>
                </value>
                <value>
                    <fullName>ParentContentTagsCategories</fullName>
                    <label>Parent Content Tags + Categories</label>
                </value>
                <value>
                    <fullName>All Articles</fullName>
                </value>
                <value>
                    <fullName>All Events</fullName>
                </value>
                <value>
                    <fullName>All Blocks</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HierarchicalOrderBy__c</fullName>
        <label>Cluster Hierarchy Order By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <label>Root to Leaf</label>
                </value>
                <value>
                    <fullName>DESC</fullName>
                    <label>Leaf to Root</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OrderByAdvance__c</fullName>
        <label>Order by Advance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderBy__c</fullName>
        <label>Order By</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Datasource__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>CreatedDate ASC</fullName>
                    <default>true</default>
                    <label>Creation Date ASC</label>
                </value>
                <value>
                    <fullName>CreatedDate DESC</fullName>
                    <label>Creation Date DESC</label>
                </value>
                <value>
                    <fullName>Name ASC</fullName>
                </value>
                <value>
                    <fullName>Name DESC</fullName>
                </value>
                <value>
                    <fullName>Category__r.Name ASC</fullName>
                    <label>Category ASC</label>
                </value>
                <value>
                    <fullName>Category__r.Name DESC</fullName>
                    <label>Category DESC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c ASC</fullName>
                    <label>Publish Start Date ASC</label>
                </value>
                <value>
                    <fullName>PublishStartDate__c DESC</fullName>
                    <label>Publish Start Date DESC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c ASC</fullName>
                    <label>Event Start Date ASC</label>
                </value>
                <value>
                    <fullName>EventStartDate__c DESC</fullName>
                    <label>Event Start Date DESC</label>
                </value>
                <value>
                    <fullName>Title__c ASC</fullName>
                    <label>Title ASC</label>
                </value>
                <value>
                    <fullName>Title__c DESC</fullName>
                    <label>Title DESC</label>
                </value>
                <value>
                    <fullName>Custom Sorting</fullName>
                </value>
                <value>
                    <fullName>Manual Order</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PageSize__c</fullName>
        <label>Page Size</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TagCriteria__c</fullName>
        <description>It&apos;s the tag criteria to filter the content on the community.</description>
        <inlineHelpText>(1 AND 2) OR 3</inlineHelpText>
        <label>Tag Criteria</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <description>Use this field to define the component title.</description>
        <label>Component Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ComponentManager.cls
public without sharing virtual class ComponentManager {
    
    //Parameters
    public String componentExternalId;
    public String clusterId;
    public String device;
    public Component__c componentRecord;
    public String componentId;
    public String navigationUrl;

    //Base atributes
    public Set<String> defaultComponentFieldSet;
    public Set<String> componentFieldSet;
    public String customPermissionEdit;
    public String customPermissionView;

    //Component Wrapper
    public ComponentWrapper cw;

    //WRAPPERS
    public class ComponentWrapper{
        @auraEnabled public CustomSettingWrapper acceleratorSettings;
        @auraEnabled public String clusterId;
        @auraEnabled public PermissionsWrapper permissions;
        @auraEnabled public MetaWrapper meta;
        @auraEnabled public DataWrapper data;
        @auraEnabled public String contentRecordTypeId;
        @auraEnabled public Boolean hasContent;
    }

    public class PermissionsWrapper{
        @auraEnabled public Boolean isEnabledEditFrame; 
        @auraEnabled public Boolean isEnabledViewFrame;
    }

    public virtual class MetaWrapper{
        @auraEnabled public ObjectComponentWrapper component;
        @auraEnabled public String objectId;
        @auraEnabled public String name;
        @auraEnabled public String navId;
        @auraEnabled public String namespace;
    }
    
    public virtual class DataWrapper{}

    //Get general component wrapper
    public ComponentWrapper getCW(){
        cw = new ComponentWrapper();
        //Looking for default cluster
        if(clusterId == null || clusterId.trim() == ''){
            clusterId = ClusterUtils.getClusterIdFromMappingObject(UserInfo.getUserId(), Network.getNetworkId());
        }

        cw.acceleratorSettings = new CustomSettingWrapper(CMSSettings__c.getInstance(), CMSContentSettings__c.getInstance(), CMSMediaElementSettings__c.getInstance());
        cw.clusterId = clusterId;
        cw.permissions = getPermissionWrapper();
        cw.meta = getMeta();
        cw.hasContent = false;

        if(cw.meta.component != null){
            String contentRTDevName = ContentUtils.rtComponentToContent.get(cw.meta.component.RecordtypeDeveloperName);
            if(contentRTDevName != null){
                cw.contentRecordTypeId = Schema.SObjectType.Content__c.getRecordTypeInfosByDeveloperName().get(GeneralUtils.prefix(contentRTDevName)).getRecordTypeId();
            }
        }
        
        cw.data = getData();
        
        return cw;
    }

    public virtual PermissionsWrapper getPermissionWrapper() {
        PermissionsWrapper pw = new PermissionsWrapper();
        pw.isEnabledEditFrame = FeatureManagement.checkPermission('CommunityEditFrame');
        pw.isEnabledViewFrame = FeatureManagement.checkPermission('CommunityViewFrame');
        
        if(!pw.isEnabledEditFrame){
            pw.isEnabledEditFrame = FeatureManagement.checkPermission(customPermissionEdit.deleteWhitespace());
        }

        if (!pw.isEnabledViewFrame){
            pw.isEnabledViewFrame = FeatureManagement.checkPermission(customPermissionView.deleteWhitespace());
        }

        return pw; 
    }

    public virtual MetaWrapper getMeta() {
        MetaWrapper mw = new MetaWrapper();
        //Default fields
        defaultComponentFieldSet = new Set<String>();
        defaultComponentFieldSet.add('Id');
        defaultComponentFieldSet.add('Name');
        defaultComponentFieldSet.add('Recordtype.DeveloperName');        
        defaultComponentFieldSet.add('Recordtype.Id');
        defaultComponentFieldSet.add('[CMS]Datasource__c');
        defaultComponentFieldSet.add('[CMS]OrderBy__c');        
        defaultComponentFieldSet.add('[CMS]OrderByAdvance__c');
        defaultComponentFieldSet.add('[CMS]HierarchicalOrderBy__c');
        defaultComponentFieldSet.add('[CMS]TagCriteria__c');
        defaultComponentFieldSet.add('[CMS]PageSize__c');
        defaultComponentFieldSet.add('[CMS]Title__c');
        defaultComponentFieldSet.addAll(componentFieldSet);
        if(String.isNotBlank(componentExternalId)){
            componentRecord = ComponentUtils.getComponent(componentExternalId, defaultComponentFieldSet, device);
        }
        else{
            componentRecord = ComponentUtils.getComponent(componentId, defaultComponentFieldSet, device);
        }

        //Translate component record
        TranslationUtils.getTranslated(componentRecord, UserInfo.getLanguage(), '[CMS]Component__c');
        
        mw.component = new ObjectComponentWrapper(componentRecord);
        mw.navId = GeneralUtils.getNavigationId(navigationUrl);
        mw.namespace = GeneralUtils.getNameSpace();
        return mw;
    }

    public virtual DataWrapper getData() {
        DataWrapper cw = new DataWrapper();
        return cw;
    }

}