src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ComponentUtils.cls
public with sharing class ComponentUtils {

	public static Component__c getComponent(String componentExternalId, set<String> fieldSet, String device){
        List<Component__c> queryResult = Database.query(GeneralUtils.prefix('SELECT ' + GeneralUtils.joinFields(fieldSet) + ' FROM [CMS]Component__c WHERE Id =: componentExternalId OR [CMS]ExternalId__c = \'' + componentExternalId + '\' LIMIT 1'));
        
        Component__c component;
        if(!queryResult.isEmpty()){
        	component = queryResult[0];
        }

        return component;
    }

}