src/objects/Component__c.object
<CustomObject>
    <description>Represents the behaviour definition for CG components that can be use in a community. For each lightning component available on the community builder, there is one component record type.</description>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and Cluster External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldsToSearch__c</fullName>
        <description>Content object fields to search for the inserted Global Search text</description>
        <inlineHelpText>Content object fields comma separated</inlineHelpText>
        <label>Fields To Search</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Component</label>
    <nameField>
        <label>Component Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner component. Each banner component has a given aspect ratio and orientation for its presentation. It also has a given behavior for presenting its content such as carousel or appear-disappear effect.</description>
        <label>Banner</label>
    </recordTypes>
    <recordTypes>
        <fullName>Search</fullName>
        <active>true</active>
        <description>Configure a new Search component. A Search has one or more related records associated to an Object.</description>
        <label>Search</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>4096</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <recordTypes>
        <fullName>Banner</fullName>
        <active>true</active>
        <description>Configure a new Banner content. This content will scroll or appear-fade inside a Banner. The data this type of content allows are Media elements</description>
        <label>Banner</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <description>Autocompleted/editable field based on Name and External Id for import/export purposes.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name and External Id for import/export purposes.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>URLMask__c</fullName>
        <label>URL Mask</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/SearchSetting__c.object
<CustomObject>
    <fields>
        <fullName>Component__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Component</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Component__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Search</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Component__c</referenceTo>
        <relationshipLabel>Search Settings</relationshipLabel>
        <relationshipName>Search_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ExternalId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Autocompleted/editable field based on Name.</description>
        <externalId>true</externalId>
        <inlineHelpText>Autocompleted/editable field based on Name.</inlineHelpText>
        <label>External Id</label>
        <length>80</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>FieldsToSearch__c</fullName>
        <description>Fields in which will be searched the inserted text</description>
        <inlineHelpText>The fields api names separeted by comma</inlineHelpText>
        <label>Fields To Search</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FieldsToShow__c</fullName>
        <description>Fields that will be shown</description>
        <inlineHelpText>Insert the fields api names separeted by comma</inlineHelpText>
        <label>Fields To Show</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Filter__c</fullName>
        <description>SOQL additional filter</description>
        <inlineHelpText>SOQL additional filter</inlineHelpText>
        <label>Filter</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IconName__c</fullName>
        <description>Name of the Lightning Icon to show next to the name</description>
        <inlineHelpText>Insert the name of a Lightning Icon. 
Ex: &quot;utility:user&quot;</inlineHelpText>
        <label>Icon Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navigation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation</label>
        <referenceTo>Navigation__c</referenceTo>
        <relationshipLabel>Search Settings</relationshipLabel>
        <relationshipName>Search_Settings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <description>API name of the Sobject</description>
        <inlineHelpText>Insert the API name of the Salesforce Object</inlineHelpText>
        <label>Object API Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PredictiveSearchRecordsNumber__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Number of records to show in the predictive search window</description>
        <inlineHelpText>Number of records to show in the predictive search window</inlineHelpText>
        <label>Predictive Search Records Number</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RecordTypeDevName__c</fullName>
        <inlineHelpText>Insert the record type developer name</inlineHelpText>
        <label>Record Type Dev Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URLParameterField__c</fullName>
        <defaultValue>&apos;Id&apos;</defaultValue>
        <label>URL Parameter Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URLParameterName__c</fullName>
        <defaultValue>&apos;Id&apos;</defaultValue>
        <label>URL Parameter Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Search Setting</label>
    <nameField>
        <label>Search Setting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SearchControllerTest.cls
@isTest
public with sharing class SearchControllerTest {
    @testSetup
    static void setup(){
        List<Component__c> compList = MockupFactory.createComponent('Search',1);
        createSearchDetail(compList.get(0), 'Banner','banner','Content__c','Name','Name,Description__c','Banner');
    }
    
    @isTest
    static void getSearchResults(){
        List<SearchSetting__c> searchDetails = [SELECT Name, ExternalId__c, URLParameterName__c, URLParameterField__c, FieldsToSearch__c, FieldsToShow__c, IconName__c, ObjectAPIName__c, RecordTypeDevName__c, Filter__c, Navigation__r.URL__c, Navigation__r.URLMask__c, PredictiveSearchRecordsNumber__c 
                                                    FROM SearchSetting__c];
        List<SearchController.SearchResultWrapper> listResult = SearchController.getSearchResults('Test', searchDetails);
        System.debug('listResult ' + JSON.serialize(listResult));
    }

    @isTest
    static void getComponent(){
        SearchController.getComponent([SELECT ExternalId__c FROM Component__c][0].ExternalId__c);
    }
    
    @isTest
    static void getSearchDetails(){
        SearchController.getSearchDetails([SELECT ExternalId__c FROM Component__c][0].ExternalId__c);
    }
    
    @isTest
    static void getPredictiveResults(){
        List<SearchSetting__c> searchDetails = [SELECT Name, ExternalId__c, URLParameterName__c, URLParameterField__c, FieldsToSearch__c, FieldsToShow__c, IconName__c, ObjectAPIName__c, RecordTypeDevName__c, Filter__c, Navigation__r.URL__c, Navigation__r.URLMask__c, PredictiveSearchRecordsNumber__c 
                                                    FROM SearchSetting__c];
        List<SearchController.PredictiveResultWrapper> listResult = SearchController.getPredictiveResults('Test', searchDetails);
        System.debug('listResult ' + JSON.serialize(listResult));
    }

    static SearchSetting__c createSearchDetail(Component__c component, String name, String sectionApiName, String objectApiName, String fieldsToSearch, String fieldsToShow, String recordTypeDevName){
        SearchSetting__c rll = new SearchSetting__c(
            												Component__c			= component.Id,
                                                            Name                    = name,
                                                            ExternalId__c           = sectionApiName,
                                                            ObjectAPIName__c        = objectApiName,
                                                            FieldsToSearch__c       = fieldsToSearch,
                                                            FieldsToShow__c         = fieldsToShow,
                                                            RecordTypeDevName__c    = recordTypeDevName
        );
        insert rll;
        return rll;
    }
}