src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Navigation__c.object
<CustomObject>
    <description>Each Navigation has an URL address. It also has a given behaviour which determines if it&apos;ll be opened in the current tab or a new tab.</description>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Navigation</label>
    <nameField>
        <label>Navigation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigations</pluralLabel>
    <recordTypes>
        <fullName>Navigation</fullName>
        <active>true</active>
        <description>Internal or external navigation points. They are mostly references to community pages.</description>
        <label>Navigation</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CG_CommunityComponentFrameControllerTest.cls
@isTest
private class CG_CommunityComponentFrameControllerTest
{
	@isTest
	static void getContentRecordtypeId()
	{
		// Given
		// Exist a sObject with recordType Article
		String rtAR = [SELECt id, name, SobjectType FROM RecordType WHERE SobjectType =: GeneralUtils.prefix('[CMS]Content__c') AND DeveloperName = 'Article'].id;

		// When
		test.startTest();
		String crtw = CG_CommunityComponentFrameController.getContentRecordtypeId('ArticleList');
		test.stopTest();

		// Then
		System.assertEquals(rtAR, crtw);

	}

	@isTest
	static void getNavigationId()
	{
		// Given 
		//Navigation Record
        Navigation__c nav = new Navigation__c(Name = 'NavTest', URL__c = 'testNav');
        insert nav;

		// When
		test.startTest();
		String navId = CG_CommunityComponentFrameController.getNavigationId('/s/testNav');
		test.stopTest();

		// Then
		System.assertNotEquals(navId, null);
	}

}