src/objects/Content__c.object
<CustomObject>
    <description>Each content is a collection of data that ultimately will be shown in a Component. That data (Its kind and quantity) depends on the Content record type</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Manage the status of the record.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                    <label>Draft</label>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
                <value>
                    <fullName>Scheduled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Content</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContentLandingHeaderControllerTest.cls
@isTest
public with sharing class ContentLandingHeaderControllerTest {
	
	@isTest 
	static void getObjectLabel() {
		ContentLandingHeaderController.getObjectLabel('[CMS]Content__c');
	}

	@isTest 
	static void getPicklistValues() {
		ContentLandingHeaderController.getPicklistValues('[CMS]Content__c','[CMS]Status__c');
	}

	@isTest 
	static void hasCreateTemplateButton() {
		ContentLandingHeaderController.hasCreateTemplateButton();
	}
	
	@isTest 
	static void hasCreateContentButton() {
		ContentLandingHeaderController.hasCreateContentButton();
	}

}